#! /bin/sh

# University College of London
# This is a script of SNS project's first step to get the <IP address, throughput> pair.
# It generates all the wget logfiles in the ./logs/ for process_logs.py to use.
#
# $Author$: Chen Xiao<uceeheh@ucl.ac.uk>
# $Date$: 18/01/2020

domain_array=(
	www.google.com
	microsoft.com
	apple.com
	youtube.com
	www.blogger.com
	support.google.com
	play.google.com
	docs.google.com
	wordpress.org
	linkedin.com
	plus.google.com
	en.wikipedia.org
	adobe.com
	accounts.google.com
	mozilla.org
	youtu.be
	github.com
	vimeo.com
	bp.blogspot.com
	drive.google.com
	googleusercontent.com
	maps.google.com
	sites.google.com
	cloudflare.com
	amazon.com
	facebook.com
	bbc.co.uk
	vk.com
	creativecommons.org
	dailymotion.com
	istockphoto.com
	line.me
	europa.eu
	live.com
	mail.google.com
	t.me
	mail.ru
	gstatic.com
	cnn.com
	paypal.com
	bbc.com
	photos.google.com
	imdb.com
	whatsapp.com
	nytimes.com
	es.wikipedia.org
	forbes.com
	developers.google.com
	google.es
	google.de
	washingtonpost.com
	msn.com
	google.com.br
	dropbox.com
	nih.gov
	uol.com.br
	fr.wikipedia.org
	pt.wikipedia.org
	hugedomains.com
	policies.google.com
	wikimedia.org
	amazon.co.jp
	feedburner.com
	slideshare.net
	google.co.jp
	globo.com
	www.yahoo.com
	buydomains.com
	networkadvertising.org
	myspace.com
	news.google.com
	google.co.uk
	reuters.com
	theguardian.com
	w3.org
	news.yahoo.com
	medium.com
	translate.google.com
	picasaweb.google.com
	change.org
	steampowered.com
	ft.com
	groups.google.com
	booking.com
	gnu.org
	issuu.com
	aol.com
	engadget.com
	code.google.com
	ig.com.br
	wsj.com
	google.fr
	apache.org
	www.wix.com
	fb.com
	jimdofree.com
	youronlinechoices.com
	tools.google.com
	cpanel.net
	wired.com
	rakuten.co.jp
	techcrunch.com
	independent.co.uk
	ebay.com
	samsung.com
	dailymail.co.uk
	thesun.co.uk
	archive.org
	hp.com
	amazon.co.uk
	de.wikipedia.org
	goo.gl
	rt.com
	huffingtonpost.com
	mediafire.com
	ipv4.google.com
	draft.blogger.com
	files.wordpress.com
	aboutads.info
	soundcloud.com
	google.ru
	myaccount.google.com
	android.com
	gravatar.com
	nasa.gov
	marketingplatform.google.com
	harvard.edu
	opera.com
	telegram.me
	un.org
	foxnews.com
	ted.com
	abril.com.br
	www.gov.uk
	fandom.com
	bing.com
	bloomberg.com
	plesk.com
	books.google.com
	oracle.com
	nypost.com
	ok.ru
	get.google.com
	twitter.com
	amazon.de
	bit.ly
	privacyshield.gov
	wikia.com
	pinterest.com
	aliexpress.com
	telegraph.co.uk
	search.google.com
	hatena.ne.jp
	elpais.com
	cnet.com
	scribd.com
	usatoday.com
	tinyurl.com
	google.it
	terra.com.br
	lefigaro.fr
	disney.com
	economist.com
	digg.com
	sedo.com
	a8.net
	rtve.es
	bt.com
	amazon.es
	ietf.org
	so-net.ne.jp
	marriott.com
	stackoverflow.com
	nature.com
	gen.xyz
	bp2.blogger.com
	instagram.com
	google.co.in
	google.ca
	dell.com
	windowsphone.com
	sports.yahoo.com
	picasa.google.com
	themeforest.net
	eventbrite.com
	google.com.tw
	rottentomatoes.com
	academia.edu
	cnbc.com
	express.co.uk
	ja.wikipedia.org
	list-manage.com
	weibo.com
	xbox.com
	detik.com
	gizmodo.com
	godaddy.com
	goo.ne.jp
	quora.com
	id.wikipedia.org
	spiegel.de
	lemonde.fr
	finance.yahoo.com
	sciencedaily.com
	secureserver.net
	bp0.blogger.com
	playstation.com
	huffpost.com
	netflix.com
	sapo.pt
	imageshack.us
	ask.fm
	vice.com
	storage.googleapis.com
	cisco.com
	bitly.com
	spotify.com
	cbc.ca
	wikihow.com
	whitehouse.gov
	pbs.org
	wp.com
	sendspace.com
	sciencemag.org
	nhk.or.jp
	google.pl
	akamaihd.net
	buzzfeed.com
	cdc.gov
	shutterstock.com
	naver.jp
	nationalgeographic.com
	webmd.com
	ovh.co.uk
	britannica.com
	ovh.com
	bp3.blogger.com
	yahoo.co.jp
	search.yahoo.com
	amazon.fr
	blackberry.com
	yelp.com
	gooyaabitemplates.com
	welt.de
	washington.edu
	unesco.org
	www.weebly.com
	adssettings.google.com
	abc.es
	depositfiles.com
	bp1.blogger.com
	addtoany.com
	bund.de
	php.net
	soratemplates.com
	m.wikipedia.org
	loc.gov
	berkeley.edu
	nokia.com
	cbsnews.com
	target.com
	000webhost.com
	e-recht24.de
	iubenda.com
	ytimg.com
	disqus.com
	news.com.au
	ucoz.ru
	mashable.com
	theatlantic.com
	surveymonkey.com
	indiatimes.com
	sky.com
	psychologytoday.com
	elmundo.es
	bandcamp.com
	stanford.edu
	dw.com
	cpanel.com
	dan.com
	theverge.com
	sfgate.com
	instructables.com
	parallels.com
	about.com
	it.wikipedia.org
	gofundme.com
	venturebeat.com
	rambler.ru
	npr.org
	ria.ru
	worldbank.org
	4shared.com
	rapidshare.com
	yandex.ru
	cornell.edu
	yadi.sk
	www.wikipedia.org
	latimes.com
	walmart.com
	ign.com
	abc.net.au
	abcnews.go.com
	asus.com
	guardian.co.uk
	goodreads.com
	www.over-blog.com
	www.skyrock.com
	kickstarter.com
	smh.com.au
	pixabay.com
	nydailynews.com
	xinhuanet.com
	wa.me
	nginx.org
	netvibes.com
	office.com
	columbia.edu
	ggpht.com
	googleblog.com
	fastcompany.com
	metro.co.uk
	channel4.com
	google.nl
	viglink.com
	princeton.edu
	espn.com
	who.int
	ovh.net
	nvidia.com
	usnews.com
	sciencedirect.com
	newsweek.com
	my.yahoo.com
	namecheap.com
	mit.edu
	doubleclick.net
	t.co
	vox.com
	pl.wikipedia.org
	mirror.co.uk
	tripadvisor.com
	urbandictionary.com
	addthis.com
	ru.wikipedia.org
	utexas.edu
	twitch.tv
	chicagotribune.com
	mega.nz
	zendesk.com
	ibm.com
	hm.com
	photobucket.com
	time.com
	allaboutcookies.org
	mysql.com
	cambridge.org
	naver.com
	umich.edu
	ea.com
	ikea.com
	fb.me
	google.co.id
	qq.com
	alibaba.com
	hollywoodreporter.com
	gmail.com
	trustpilot.com
	box.com
	thetimes.co.uk
	shopify.com
	biglobe.ne.jp
	businessinsider.com
	lycos.com
	newyorker.com
	viagens.com.br
	amzn.to
	example.com
	www.canalblog.com
	epa.gov
	state.gov
	bloglovin.com
	clickbank.net
	standard.co.uk
	fda.gov
	ehow.com
	springer.com
	ameblo.jp
	ox.ac.uk
	nikkei.com
	vchecks.me
	apachefriends.org
	foursquare.com
	ftc.gov
	upenn.edu
	sina.com.cn
	chinadaily.com.cn
	gesetze-im-internet.de
	megaupload.com
	wiktionary.org
	eonline.com
	prezi.com
	dreamstime.com
	one.com
	thedailybeast.com
	wiley.com
	ebay.co.uk
	last.fm
	dribbble.com
	geocities.jp
	plos.org
	imgur.com
	liveinternet.ru
	thenextweb.com
	offset.com
	orange.fr
	xing.com
	storage.canalblog.com
	eff.org
	politico.com
	digitaltrends.com
	asahi.com
	businesswire.com
	adweek.com
	scoop.it
	lifehacker.com
	variety.com
	home.neustar
	autodesk.com
	steamcommunity.com
	about.me
	calameo.com
	theglobeandmail.com
	quantcast.com
	histats.com
	www.nhs.uk
	fedoraproject.org
	inc.com
	seattletimes.com
	psu.edu
	biblegateway.com
	scientificamerican.com
	zdnet.com
	ibtimes.com
	merriam-webster.com
	repubblica.it
	nbcnews.com
	cocolog-nifty.com
	arxiv.org
	boston.com
	mlb.com
	e-monsite.com
	skype.com
	ssl-images-amazon.com
	allrecipes.com
	tabelog.com
	alexa.com
	nba.com
	answers.com
	ca.gov
	sakura.ne.jp
	fortune.com
	ap.org
	nicovideo.jp
	kinja.com
	pastebin.com
	evernote.com
	mercurynews.com
	usgs.gov
	arstechnica.com
	mayoclinic.org
	airbnb.com
	espn.go.com
	redhat.com
	csmonitor.com
	amazon.ca
	vkontakte.ru
	livescience.com
	feedproxy.google.com
	usa.gov
	iso.org
	entrepreneur.com
	calendar.google.com
	jstor.org
	fifa.com
	video.google.com
	pixnet.net
	afternic.com
	greenpeace.org
	nginx.com
	fool.com
	dictionary.com
	siemens.com
	ndtv.com
	pcmag.com
	cmu.edu
	discord.gg
	answers.yahoo.com
	wattpad.com
	daum.net
)

rm -f logfile*

cat chenxiao.icon
echo "|        \033[33mFetching <IP, Throughput> Script v0.0.1\033[0m       |"
echo "|           $ \033[34mChen Xiao \033[0m <uceeheh@ucl.ac.uk> $         |"
echo "\n\nTHIS MAY TAKE A WHILE, PLEASE BE PATIENT WHILE THE SCRIPT IS RUNNING..."

#echo ${domain_array[@]}
length=${#domain_array[@]}

errflag=0
for name in ${domain_array[@]}
do	
	errflag=0
	printf "%-20s" $name":"
	printf "["
	# 40 times of wget, considering the initial congestion window size is 10
	for idx in {0..39}
	do
		printf "▓"
		wget --tries=1 --connect-timeout=3 --report-speed=bits --append-output=./logs/logfile"_$name"  -O /dev/null $name
		if [ $? != 0 ]
		then
			echo "\n\033[31m"$name" connection failed, go to the next domain.\033[0m"
			errflag=1
			break
		fi
	done;

	if [ $errflag == 0 ]
	then
		echo "]"
	fi
done;

echo "\nFinished!";
