--2020-02-25 22:35:25--  https://helapco.gr/pdf/Global_Market_Outlook_2015_-2019_lr_v23.pdf%0D
Resolving helapco.gr (helapco.gr)... --2020-02-25 22:35:25--  https://helapco.gr/pdf/Global_Market_Outlook_2015_-2019_lr_v23.pdf%0D
Resolving helapco.gr (helapco.gr)... 194.93.58.31
Connecting to helapco.gr (helapco.gr)|194.93.58.31|:443... 194.93.58.31
Connecting to helapco.gr (helapco.gr)|194.93.58.31|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:27 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

