--2020-02-25 21:55:58--  http://postetelecom.gouv.cg/discours_ministre/Discours_MPTEN_Casablanca_Maroc.pdf%0D
Resolving postetelecom.gouv.cg (postetelecom.gouv.cg)... --2020-02-25 21:55:58--  http://postetelecom.gouv.cg/discours_ministre/Discours_MPTEN_Casablanca_Maroc.pdf%0D
Resolving postetelecom.gouv.cg (postetelecom.gouv.cg)... 198.136.54.34
Connecting to postetelecom.gouv.cg (postetelecom.gouv.cg)|198.136.54.34|:80... connected.
HTTP request sent, awaiting response... 198.136.54.34
Connecting to postetelecom.gouv.cg (postetelecom.gouv.cg)|198.136.54.34|:80... 301 Moved Permanently
Location: https://postetelecom.gouv.cg/discours_ministre/Discours_MPTEN_Casablanca_Maroc.pdf%0d [following]
--2020-02-25 21:55:58--  https://postetelecom.gouv.cg/discours_ministre/Discours_MPTEN_Casablanca_Maroc.pdf%0d
Connecting to postetelecom.gouv.cg (postetelecom.gouv.cg)|198.136.54.34|:443... connected.
HTTP request sent, awaiting response... connected.
301 Moved Permanently
Location: https://postetelecom.gouv.cg/discours_ministre/Discours_MPTEN_Casablanca_Maroc.pdf%0d [following]
--2020-02-25 21:55:58--  https://postetelecom.gouv.cg/discours_ministre/Discours_MPTEN_Casablanca_Maroc.pdf%0d
Connecting to postetelecom.gouv.cg (postetelecom.gouv.cg)|198.136.54.34|:443... connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:01 ERROR 404: Not Found.

Read error (Connection timed out) in headers.
Giving up.

