--2020-02-25 22:35:28--  http://www.kosmonaftis.gr/gomath/math_algeo/algeo_trianatomy.pdf%0D
Resolving www.kosmonaftis.gr (www.kosmonaftis.gr)... --2020-02-25 22:35:28--  http://www.kosmonaftis.gr/gomath/math_algeo/algeo_trianatomy.pdf%0D
Resolving www.kosmonaftis.gr (www.kosmonaftis.gr)... 94.130.71.189
Connecting to www.kosmonaftis.gr (www.kosmonaftis.gr)|94.130.71.189|:80... 94.130.71.189
Connecting to www.kosmonaftis.gr (www.kosmonaftis.gr)|94.130.71.189|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

