--2020-02-25 22:35:09--  https://www.ich.gr/files/odigies_aimolipsias.pdf%0D
Resolving www.ich.gr (www.ich.gr)... 178.63.25.232
Connecting to www.ich.gr (www.ich.gr)|178.63.25.232|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.ich.gr/el/files/odigies_aimolipsias.pdf [following]
--2020-02-25 22:35:09--  https://www.ich.gr/el/files/odigies_aimolipsias.pdf
Reusing existing connection to www.ich.gr:443.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:09 ERROR 404: Not Found.

--2020-02-25 22:35:09--  https://www.ich.gr/files/odigies_aimolipsias.pdf%0D
Resolving www.ich.gr (www.ich.gr)... 178.63.25.232
Connecting to www.ich.gr (www.ich.gr)|178.63.25.232|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.ich.gr/el/files/odigies_aimolipsias.pdf [following]
--2020-02-25 22:35:10--  https://www.ich.gr/el/files/odigies_aimolipsias.pdf
Reusing existing connection to www.ich.gr:443.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:10 ERROR 404: Not Found.

