--2020-02-25 22:34:52--  https://www.espa.gr/elibrary/%25CE%2595%25CE%2595_2020.pdf%0D
Resolving www.espa.gr (www.espa.gr)... 195.167.92.149
Connecting to www.espa.gr (www.espa.gr)|195.167.92.149|:443... connected.
Unable to establish SSL connection.
--2020-02-25 22:34:53--  https://www.espa.gr/elibrary/%25CE%2595%25CE%2595_2020.pdf%0D
Resolving www.espa.gr (www.espa.gr)... 195.167.92.149
Connecting to www.espa.gr (www.espa.gr)|195.167.92.149|:443... connected.
Unable to establish SSL connection.
