--2020-02-25 21:01:42--  http://www.bahamasnationalarchives.bs/assets/smyth.pdf%0D
Resolving www.bahamasnationalarchives.bs (www.bahamasnationalarchives.bs)... 206.188.192.19
Connecting to www.bahamasnationalarchives.bs (www.bahamasnationalarchives.bs)|206.188.192.19|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:01:43 ERROR 404: Not Found.

--2020-02-25 21:13:11--  http://www.bahamasnationalarchives.bs/assets/smyth.pdf%0D
Resolving www.bahamasnationalarchives.bs (www.bahamasnationalarchives.bs)... 206.188.192.19
Connecting to www.bahamasnationalarchives.bs (www.bahamasnationalarchives.bs)|206.188.192.19|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:11 ERROR 404: Not Found.

