--2020-02-25 22:35:13--  https://allwan.gr/images/pdf/RB750r2.pdf%0D
Resolving allwan.gr (allwan.gr)... 93.174.127.155
Connecting to allwan.gr (allwan.gr)|93.174.127.155|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.allwan.gr/index.php [following]
--2020-02-25 22:35:15--  https://www.allwan.gr/index.php
Resolving www.allwan.gr (www.allwan.gr)... 93.174.127.155
Connecting to www.allwan.gr (www.allwan.gr)|93.174.127.155|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 3.60M
    50K ........                                               1.24G=0.1s

2020-02-25 22:35:16 (4.22 Mb/s) - ‘/dev/null’ saved [60034]

--2020-02-25 22:35:16--  https://allwan.gr/images/pdf/RB750r2.pdf%0D
Resolving allwan.gr (allwan.gr)... 93.174.127.155
Connecting to allwan.gr (allwan.gr)|93.174.127.155|:443... connected.
--2020-02-25 22:35:16--  https://allwan.gr/images/pdf/RB750r2.pdf%0D
Resolving allwan.gr (allwan.gr)... 93.174.127.155
Connecting to allwan.gr (allwan.gr)|93.174.127.155|:443... HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.allwan.gr/index.php [following]
--2020-02-25 22:35:16--  https://www.allwan.gr/index.php
Resolving www.allwan.gr (www.allwan.gr)... 93.174.127.155
Connecting to www.allwan.gr (www.allwan.gr)|93.174.127.155|:443... connected.
301 Moved Permanently
Location: https://www.allwan.gr/index.php [following]
--2020-02-25 22:35:17--  https://www.allwan.gr/index.php
Resolving www.allwan.gr (www.allwan.gr)... 93.174.127.155
Connecting to www.allwan.gr (www.allwan.gr)|93.174.127.155|:443... connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Giving up.

Read error (Connection timed out) in headers.
Giving up.

