--2020-02-25 21:41:13--  https://particuliers.societegenerale.td/fileadmin/user_upload/tchad/CEMAC_reglementation_des_changes.pdf%0D
Resolving particuliers.societegenerale.td (particuliers.societegenerale.td)... 194.177.39.82
Connecting to particuliers.societegenerale.td (particuliers.societegenerale.td)|194.177.39.82|:443... connected.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M956
Location: https://particuliers.societegenerale.td/fileadmin/user_upload/tchad/CEMAC_reglementation_des_changes.pdf%0D/ [following]
--2020-02-25 21:41:13--  https://particuliers.societegenerale.td/fileadmin/user_upload/tchad/CEMAC_reglementation_des_changes.pdf%0D/
Reusing existing connection to particuliers.societegenerale.td:443.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:13 ERROR 404: Not Found.

--2020-02-25 21:42:04--  https://particuliers.societegenerale.td/fileadmin/user_upload/tchad/CEMAC_reglementation_des_changes.pdf%0D
Resolving particuliers.societegenerale.td (particuliers.societegenerale.td)... 194.177.39.82
Connecting to particuliers.societegenerale.td (particuliers.societegenerale.td)|194.177.39.82|:443... connected.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M956
Location: https://particuliers.societegenerale.td/fileadmin/user_upload/tchad/CEMAC_reglementation_des_changes.pdf%0D/ [following]
--2020-02-25 21:42:04--  https://particuliers.societegenerale.td/fileadmin/user_upload/tchad/CEMAC_reglementation_des_changes.pdf%0D/
Reusing existing connection to particuliers.societegenerale.td:443.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:04 ERROR 404: Not Found.

