--2020-02-25 22:35:08--  http://www.teiath.gr/userfiles/khitas/documents/en/odigos_spoudon_eng.pdf%0D
Resolving www.teiath.gr (www.teiath.gr)... 195.130.100.83
Connecting to www.teiath.gr (www.teiath.gr)|195.130.100.83|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:08 ERROR 404: Not Found.

--2020-02-25 22:35:09--  http://www.teiath.gr/userfiles/khitas/documents/en/odigos_spoudon_eng.pdf%0D
Resolving www.teiath.gr (www.teiath.gr)... 195.130.100.83
Connecting to www.teiath.gr (www.teiath.gr)|195.130.100.83|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:09 ERROR 404: Not Found.

