--2020-02-25 21:41:22--  http://numerique.td/wp-content/uploads/2019/07/PROGRAMME-COMPLET.pdf%0D
Resolving numerique.td (numerique.td)... 54.36.91.62
Connecting to numerique.td (numerique.td)|54.36.91.62|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:25 ERROR 404: Not Found.

--2020-02-25 21:42:10--  http://numerique.td/wp-content/uploads/2019/07/PROGRAMME-COMPLET.pdf%0D
Resolving numerique.td (numerique.td)... 54.36.91.62
Connecting to numerique.td (numerique.td)|54.36.91.62|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:11 ERROR 404: Not Found.

