--2020-02-25 22:35:09--  http://www.cosmocom.gr/wp-content/uploads/2013/05/Intro_to_mpls.pdf%0D
Resolving www.cosmocom.gr (www.cosmocom.gr)... 46.249.204.22
Connecting to www.cosmocom.gr (www.cosmocom.gr)|46.249.204.22|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.cosmocom.gr/wp-content/uploads/2013/05/Intro_to_mpls.pdf%0d [following]
--2020-02-25 22:35:10--  https://www.cosmocom.gr/wp-content/uploads/2013/05/Intro_to_mpls.pdf%0d
Connecting to www.cosmocom.gr (www.cosmocom.gr)|46.249.204.22|:443... connected.
HTTP request sent, awaiting response... --2020-02-25 22:35:10--  http://www.cosmocom.gr/wp-content/uploads/2013/05/Intro_to_mpls.pdf%0D
Resolving www.cosmocom.gr (www.cosmocom.gr)... 46.249.204.22
Connecting to www.cosmocom.gr (www.cosmocom.gr)|46.249.204.22|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.cosmocom.gr/wp-content/uploads/2013/05/Intro_to_mpls.pdf%0d [following]
--2020-02-25 22:35:10--  https://www.cosmocom.gr/wp-content/uploads/2013/05/Intro_to_mpls.pdf%0d
Connecting to www.cosmocom.gr (www.cosmocom.gr)|46.249.204.22|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:10 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:10 ERROR 404: Not Found.

