--2020-02-25 22:35:13--  https://www.forin.gr/files/74971%3Finline%3D1%0D
Resolving www.forin.gr (www.forin.gr)... 195.201.55.24
Connecting to www.forin.gr (www.forin.gr)|195.201.55.24|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:13 ERROR 404: Not Found.

--2020-02-25 22:35:16--  https://www.forin.gr/files/74971%3Finline%3D1%0D
Resolving www.forin.gr (www.forin.gr)... 195.201.55.24
Connecting to www.forin.gr (www.forin.gr)|195.201.55.24|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:16 ERROR 404: Not Found.

