--2020-02-25 22:43:49--  http://www.archivioapostolicovaticano.va/content/dam/aav/documenti/SB_01.pdf%0D
Resolving www.archivioapostolicovaticano.va (www.archivioapostolicovaticano.va)... 185.152.70.30
Connecting to www.archivioapostolicovaticano.va (www.archivioapostolicovaticano.va)|185.152.70.30|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:49 ERROR 404: Not Found.

