--2020-02-25 21:41:10--  https://site.uvt.td/ressources/depliant.pdf%0D
Resolving site.uvt.td (site.uvt.td)... 213.186.33.186
Connecting to site.uvt.td (site.uvt.td)|213.186.33.186|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:11 ERROR 404: Not Found.

--2020-02-25 21:42:04--  https://site.uvt.td/ressources/depliant.pdf%0D
Resolving site.uvt.td (site.uvt.td)... 213.186.33.186
Connecting to site.uvt.td (site.uvt.td)|213.186.33.186|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:04 ERROR 404: Not Found.

