--2020-02-25 23:57:10--  http://tataco.ms/pYVBnQ%0D
Resolving tataco.ms (tataco.ms)... 52.21.33.16
Connecting to tataco.ms (tataco.ms)|52.21.33.16|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.tatacommunications.com/404?link=pYVBnQ%0D [following]
--2020-02-25 23:57:10--  http://www.tatacommunications.com/404?link=pYVBnQ%0D
Resolving www.tatacommunications.com (www.tatacommunications.com)... 64.185.181.238
Connecting to www.tatacommunications.com (www.tatacommunications.com)|64.185.181.238|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.tatacommunications.com/404?link=pYVBnQ%0D [following]
--2020-02-25 23:57:10--  https://www.tatacommunications.com/404?link=pYVBnQ%0D
Connecting to www.tatacommunications.com (www.tatacommunications.com)|64.185.181.238|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:11 ERROR 404: Not Found.

