--2020-02-25 22:35:04--  https://www.meteo.gr/pdf/intro_solar_system.pdf%0D
Resolving www.meteo.gr (www.meteo.gr)... 185.70.76.135
Connecting to www.meteo.gr (www.meteo.gr)|185.70.76.135|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:04 ERROR 400: Bad Request.

--2020-02-25 22:35:06--  https://www.meteo.gr/pdf/intro_solar_system.pdf%0D
Resolving www.meteo.gr (www.meteo.gr)... 185.70.76.135
Connecting to www.meteo.gr (www.meteo.gr)|185.70.76.135|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:07 ERROR 400: Bad Request.

