--2020-02-25 21:41:05--  http://www.cesc.td/images/Faire_des_affaires_au_Tchad.pdf%0D
Resolving www.cesc.td (www.cesc.td)... 162.215.253.97
Connecting to www.cesc.td (www.cesc.td)|162.215.253.97|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.cesc.td/fr/images/Faire_des_affaires_au_Tchad.pdf [following]
--2020-02-25 21:41:05--  http://www.cesc.td/fr/images/Faire_des_affaires_au_Tchad.pdf
Reusing existing connection to www.cesc.td:80.
HTTP request sent, awaiting response... 404 Affichage introuvable [name, type, prefix] : category, pdf, contentView
2020-02-25 21:41:06 ERROR 404: Affichage introuvable [name, type, prefix] : category, pdf, contentView.

--2020-02-25 21:41:06--  http://www.cesc.td/images/Discours_de_cloture_2%25C3%25A8me_Session_sept_2018.pdf%0D
Resolving www.cesc.td (www.cesc.td)... 162.215.253.97
Connecting to www.cesc.td (www.cesc.td)|162.215.253.97|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.cesc.td/fr/images/Discours_de_cloture_2%C3%A8me_Session_sept_2018.pdf [following]
--2020-02-25 21:41:06--  http://www.cesc.td/fr/images/Discours_de_cloture_2%C3%A8me_Session_sept_2018.pdf
Reusing existing connection to www.cesc.td:80.
HTTP request sent, awaiting response... 404 Affichage introuvable [name, type, prefix] : category, pdf, contentView
2020-02-25 21:41:06 ERROR 404: Affichage introuvable [name, type, prefix] : category, pdf, contentView.

--2020-02-25 21:42:02--  http://www.cesc.td/images/Faire_des_affaires_au_Tchad.pdf%0D
Resolving www.cesc.td (www.cesc.td)... 162.215.253.97
Connecting to www.cesc.td (www.cesc.td)|162.215.253.97|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.cesc.td/fr/images/Faire_des_affaires_au_Tchad.pdf [following]
--2020-02-25 21:42:02--  http://www.cesc.td/fr/images/Faire_des_affaires_au_Tchad.pdf
Reusing existing connection to www.cesc.td:80.
HTTP request sent, awaiting response... 404 Affichage introuvable [name, type, prefix] : category, pdf, contentView
2020-02-25 21:42:02 ERROR 404: Affichage introuvable [name, type, prefix] : category, pdf, contentView.

--2020-02-25 21:42:02--  http://www.cesc.td/images/Discours_de_cloture_2%25C3%25A8me_Session_sept_2018.pdf%0D
Resolving www.cesc.td (www.cesc.td)... 162.215.253.97
Connecting to www.cesc.td (www.cesc.td)|162.215.253.97|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.cesc.td/fr/images/Discours_de_cloture_2%C3%A8me_Session_sept_2018.pdf [following]
--2020-02-25 21:42:03--  http://www.cesc.td/fr/images/Discours_de_cloture_2%C3%A8me_Session_sept_2018.pdf
Reusing existing connection to www.cesc.td:80.
HTTP request sent, awaiting response... 404 Affichage introuvable [name, type, prefix] : category, pdf, contentView
2020-02-25 21:42:03 ERROR 404: Affichage introuvable [name, type, prefix] : category, pdf, contentView.

