--2020-02-25 22:35:09--  https://www.ikea.gr/pdf/70104099.pdf%0D
Resolving www.ikea.gr (www.ikea.gr)... 52.137.27.140
Connecting to www.ikea.gr (www.ikea.gr)|52.137.27.140|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:09 ERROR 400: Bad Request.

--2020-02-25 22:35:10--  https://www.ikea.gr/pdf/70104099.pdf%0D
Resolving www.ikea.gr (www.ikea.gr)... 52.137.27.140
Connecting to www.ikea.gr (www.ikea.gr)|52.137.27.140|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:10 ERROR 400: Bad Request.

