--2020-02-25 21:56:08--  https://www.arpce.cg/upload/publications/dcision_355.pdf%0D
Resolving www.arpce.cg (www.arpce.cg)... 151.80.240.56
Connecting to www.arpce.cg (www.arpce.cg)|151.80.240.56|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 21:56:08 ERROR 403: Forbidden.

--2020-02-25 21:56:12--  https://www.arpce.cg/upload/publications/dcision_355.pdf%0D
Resolving www.arpce.cg (www.arpce.cg)... 151.80.240.56
Connecting to www.arpce.cg (www.arpce.cg)|151.80.240.56|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 21:56:12 ERROR 403: Forbidden.

