--2020-02-25 21:56:21--  http://www.armp.cg/Portals/0/Pdf/PPM/MJDH.pdf%0D
Resolving www.armp.cg (www.armp.cg)... --2020-02-25 21:56:21--  http://www.armp.cg/Portals/0/Pdf/PPM/MJDH.pdf%0D
Resolving www.armp.cg (www.armp.cg)... 208.88.76.71
Connecting to www.armp.cg (www.armp.cg)|208.88.76.71|:80... 208.88.76.71
Connecting to www.armp.cg (www.armp.cg)|208.88.76.71|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 21:56:22 ERROR 400: Bad Request.

400 Bad Request
2020-02-25 21:56:22 ERROR 400: Bad Request.

