--2020-02-26 00:02:37--  http://www.naurugov.nr/media/57501/nauru_bulletin__13_21nov2018__181_.pdf%0D
Resolving www.naurugov.nr (www.naurugov.nr)... failed: Connection timed out.
wget: unable to resolve host address ‘www.naurugov.nr’
--2020-02-26 00:02:40--  http://www.naurugov.nr/media/63932/nauru_bulletin__16_05oct2019__200_.pdf%0D
Resolving www.naurugov.nr (www.naurugov.nr)... failed: Connection timed out.
wget: unable to resolve host address ‘www.naurugov.nr’
