--2020-02-25 22:35:10--  http://edu.eap.gr/pli/pli23/documents/Parallila_Keimena/Cellular_Communications.pdf%0D
Resolving edu.eap.gr (edu.eap.gr)... --2020-02-25 22:35:10--  http://edu.eap.gr/pli/pli23/documents/Parallila_Keimena/Cellular_Communications.pdf%0D
Resolving edu.eap.gr (edu.eap.gr)... 193.108.160.197
Connecting to edu.eap.gr (edu.eap.gr)|193.108.160.197|:80... 193.108.160.197
Connecting to edu.eap.gr (edu.eap.gr)|193.108.160.197|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:10 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:10 ERROR 404: Not Found.

