--2020-02-25 22:34:51--  https://www.aueb.gr/career/Coverletterpres.pdf%0D
Resolving www.aueb.gr (www.aueb.gr)... 195.251.255.156
Connecting to www.aueb.gr (www.aueb.gr)|195.251.255.156|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:52 ERROR 404: Not Found.

--2020-02-25 22:34:52--  https://www.aueb.gr/career/Coverletterpres.pdf%0D
Resolving www.aueb.gr (www.aueb.gr)... 195.251.255.156
Connecting to www.aueb.gr (www.aueb.gr)|195.251.255.156|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:53 ERROR 404: Not Found.

