--2020-02-25 22:35:24--  http://www.aeavellas.gr/100years/content/100yearsAEAVellas.pdf%0D
Resolving www.aeavellas.gr (www.aeavellas.gr)... --2020-02-25 22:35:24--  http://www.aeavellas.gr/100years/content/100yearsAEAVellas.pdf%0D
Resolving www.aeavellas.gr (www.aeavellas.gr)... 62.103.107.48
Connecting to www.aeavellas.gr (www.aeavellas.gr)|62.103.107.48|:80... 62.103.107.48
Connecting to www.aeavellas.gr (www.aeavellas.gr)|62.103.107.48|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:25 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:25 ERROR 404: Not Found.

