--2020-02-25 21:56:16--  http://pssn.cg/images/Bulletins/LOGICIEL-ESPION.pdf%0D
Resolving pssn.cg (pssn.cg)... --2020-02-25 21:56:16--  http://pssn.cg/images/Bulletins/LOGICIEL-ESPION.pdf%0D
Resolving pssn.cg (pssn.cg)... 164.132.235.17
Connecting to pssn.cg (pssn.cg)|164.132.235.17|:80... connected.
HTTP request sent, awaiting response... 164.132.235.17
Connecting to pssn.cg (pssn.cg)|164.132.235.17|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:16 ERROR 404: Not Found.

404 Not Found
2020-02-25 21:56:16 ERROR 404: Not Found.

