--2020-02-25 21:55:56--  http://pharmacredit.cg/telechargement/liste.pdf%0D
Resolving pharmacredit.cg (pharmacredit.cg)... --2020-02-25 21:55:56--  http://pharmacredit.cg/telechargement/liste.pdf%0D
Resolving pharmacredit.cg (pharmacredit.cg)... 213.186.33.4
Connecting to pharmacredit.cg (pharmacredit.cg)|213.186.33.4|:80... connected.
HTTP request sent, awaiting response... 213.186.33.4
Connecting to pharmacredit.cg (pharmacredit.cg)|213.186.33.4|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:55:56 ERROR 404: Not Found.

404 Not Found
2020-02-25 21:55:56 ERROR 404: Not Found.

