--2020-02-25 22:34:47--  http://www.metrologia.gr/JCGM_104_2009_E.pdf%0D
Resolving www.metrologia.gr (www.metrologia.gr)... 212.95.36.177
Connecting to www.metrologia.gr (www.metrologia.gr)|212.95.36.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:47 ERROR 404: Not Found.

--2020-02-25 22:34:47--  http://www.metrologia.gr/JCGM_104_2009_E.pdf%0D
Resolving www.metrologia.gr (www.metrologia.gr)... 212.95.36.177
Connecting to www.metrologia.gr (www.metrologia.gr)|212.95.36.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:47 ERROR 404: Not Found.

