--2020-02-25 21:41:13--  http://www.ceni.td/sites/default/files/dossier/Chronogramme.pdf%0D
Resolving www.ceni.td (www.ceni.td)... 91.191.158.199
Connecting to www.ceni.td (www.ceni.td)|91.191.158.199|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 21:41:13 ERROR 400: Bad Request.

--2020-02-25 21:42:04--  http://www.ceni.td/sites/default/files/dossier/Chronogramme.pdf%0D
Resolving www.ceni.td (www.ceni.td)... 91.191.158.199
Connecting to www.ceni.td (www.ceni.td)|91.191.158.199|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 21:42:04 ERROR 400: Bad Request.

