--2020-02-25 21:01:58--  http://www.scb.gov.bs/documents/MOU-GFSR.pdf%0D
Resolving www.scb.gov.bs (www.scb.gov.bs)... 66.96.146.52
Connecting to www.scb.gov.bs (www.scb.gov.bs)|66.96.146.52|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 21:01:58 ERROR 400: Bad Request.

--2020-02-25 21:13:23--  http://www.scb.gov.bs/documents/MOU-GFSR.pdf%0D
Resolving www.scb.gov.bs (www.scb.gov.bs)... 66.96.146.52
Connecting to www.scb.gov.bs (www.scb.gov.bs)|66.96.146.52|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 21:13:23 ERROR 400: Bad Request.

