--2020-02-26 00:21:11--  http://nr.mp/79Wl50xzyhe%0D
Resolving nr.mp (nr.mp)... 54.241.242.79
Connecting to nr.mp (nr.mp)|54.241.242.79|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://nearmap.com [following]
--2020-02-26 00:21:12--  http://nearmap.com/
Resolving nearmap.com (nearmap.com)... 54.241.16.15
Connecting to nearmap.com (nearmap.com)|54.241.16.15|:80... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: http://au.nearmap.com/ [following]
--2020-02-26 00:21:12--  http://au.nearmap.com/
Resolving au.nearmap.com (au.nearmap.com)... 54.252.98.246
Connecting to au.nearmap.com (au.nearmap.com)|54.252.98.246|:80... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: http://www.nearmap.com.au [following]
--2020-02-26 00:21:13--  http://www.nearmap.com.au/
Resolving www.nearmap.com.au (www.nearmap.com.au)... 151.101.18.224
Connecting to www.nearmap.com.au (www.nearmap.com.au)|151.101.18.224|:80... connected.
HTTP request sent, awaiting response... 301 Moved permanently
Location: https://www.nearmap.com/au/en/ [following]
--2020-02-26 00:21:13--  https://www.nearmap.com/au/en/
Resolving www.nearmap.com (www.nearmap.com)... 151.101.18.224
Connecting to www.nearmap.com (www.nearmap.com)|151.101.18.224|:443... connected.
HTTP request sent, awaiting response... 301 Moved permanently
Location: /au/en [following]
--2020-02-26 00:21:13--  https://www.nearmap.com/au/en
Connecting to www.nearmap.com (www.nearmap.com)|151.101.18.224|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74150 (72K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 69%  371M 0s
    50K .......... .......... ..                              100%  560M=0.001s

2020-02-26 00:21:13 (414 Mb/s) - ‘/dev/null’ saved [74150/74150]

--2020-02-26 00:21:13--  http://nr.mp/79Wl50xzyhe%0D
Resolving nr.mp (nr.mp)... 54.241.242.79
Connecting to nr.mp (nr.mp)|54.241.242.79|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://nearmap.com [following]
--2020-02-26 00:21:13--  http://nearmap.com/
Resolving nearmap.com (nearmap.com)... 54.241.16.15
Connecting to nearmap.com (nearmap.com)|54.241.16.15|:80... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: http://au.nearmap.com/ [following]
--2020-02-26 00:21:13--  http://au.nearmap.com/
Resolving au.nearmap.com (au.nearmap.com)... 54.252.98.246
Connecting to au.nearmap.com (au.nearmap.com)|54.252.98.246|:80... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: http://www.nearmap.com.au [following]
--2020-02-26 00:21:14--  http://www.nearmap.com.au/
Resolving www.nearmap.com.au (www.nearmap.com.au)... 151.101.18.224
Connecting to www.nearmap.com.au (www.nearmap.com.au)|151.101.18.224|:80... connected.
HTTP request sent, awaiting response... 301 Moved permanently
Location: https://www.nearmap.com/au/en/ [following]
--2020-02-26 00:21:14--  https://www.nearmap.com/au/en/
Resolving www.nearmap.com (www.nearmap.com)... 151.101.18.224
Connecting to www.nearmap.com (www.nearmap.com)|151.101.18.224|:443... connected.
HTTP request sent, awaiting response... 301 Moved permanently
Location: /au/en [following]
--2020-02-26 00:21:14--  https://www.nearmap.com/au/en
Connecting to www.nearmap.com (www.nearmap.com)|151.101.18.224|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74150 (72K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 69%  408M 0s
    50K .......... .......... ..                              100% 1.01G=0.001s

2020-02-26 00:21:14 (500 Mb/s) - ‘/dev/null’ saved [74150/74150]

