--2020-02-25 22:34:46--  https://www.pothen.gr/n3213.pdf%0D
Resolving www.pothen.gr (www.pothen.gr)... 84.205.254.221
Connecting to www.pothen.gr (www.pothen.gr)|84.205.254.221|:443... connected.
HTTP request sent, awaiting response... --2020-02-25 22:34:47--  https://www.pothen.gr/n3213.pdf%0D
Resolving www.pothen.gr (www.pothen.gr)... 84.205.254.221
Connecting to www.pothen.gr (www.pothen.gr)|84.205.254.221|:443... 404 Not Found
2020-02-25 22:34:47 ERROR 404: Not Found.

connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:47 ERROR 404: Not Found.

