--2020-02-25 23:57:36--  https://kiwifar.ms/attachments/guntherteschrapsheet-pdf.64305/%0D
Resolving kiwifar.ms (kiwifar.ms)... 104.27.162.162, 104.27.163.162
Connecting to kiwifar.ms (kiwifar.ms)|104.27.162.162|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://kiwifarms.net/attachments/guntherteschrapsheet-pdf.64305/%0D [following]
--2020-02-25 23:57:36--  https://kiwifarms.net/attachments/guntherteschrapsheet-pdf.64305/%0D
Resolving kiwifarms.net (kiwifarms.net)... 104.26.8.145, 104.26.9.145
Connecting to kiwifarms.net (kiwifarms.net)|104.26.8.145|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:38 ERROR 404: Not Found.

