--2020-02-25 21:41:13--  http://www.onrtv.td/upld/doc/ar/onrtv-1.pdf%0D
Resolving www.onrtv.td (www.onrtv.td)... 199.16.131.163
Connecting to www.onrtv.td (www.onrtv.td)|199.16.131.163|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: /SpNOk/upld/doc/ar/onrtv-1.pdf%0D [following]
--2020-02-25 21:41:14--  http://www.onrtv.td/SpNOk/upld/doc/ar/onrtv-1.pdf%0D
Connecting to www.onrtv.td (www.onrtv.td)|199.16.131.163|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: /upld/doc/ar/onrtv-1.pdf%0D [following]
--2020-02-25 21:41:14--  http://www.onrtv.td/upld/doc/ar/onrtv-1.pdf%0D
Connecting to www.onrtv.td (www.onrtv.td)|199.16.131.163|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Giving up.

--2020-02-25 21:42:05--  http://www.onrtv.td/upld/doc/ar/onrtv-1.pdf%0D
Resolving www.onrtv.td (www.onrtv.td)... 199.16.131.163
Connecting to www.onrtv.td (www.onrtv.td)|199.16.131.163|:80... failed: Connection timed out.
Giving up.

