--2020-02-25 21:56:22--  http://www.assemblee-nationale.cg/wp-content/uploads/2019/06/Mot_du_PAN_session_cloture_troisieme_session_ordinaire_du_02_juin_au_13_aout_2018.pdf%0D
Resolving www.assemblee-nationale.cg (www.assemblee-nationale.cg)... --2020-02-25 21:56:22--  http://www.assemblee-nationale.cg/wp-content/uploads/2019/06/Mot_du_PAN_session_cloture_troisieme_session_ordinaire_du_02_juin_au_13_aout_2018.pdf%0D
Resolving www.assemblee-nationale.cg (www.assemblee-nationale.cg)... 196.40.100.202
Connecting to www.assemblee-nationale.cg (www.assemblee-nationale.cg)|196.40.100.202|:80... 196.40.100.202
Connecting to www.assemblee-nationale.cg (www.assemblee-nationale.cg)|196.40.100.202|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
404 Not Found
2020-02-25 21:56:24 ERROR 404: Not Found.

2020-02-25 21:56:24 ERROR 404: Not Found.

