--2020-02-25 22:34:50--  http://www.cres.gr/kape/education/3.CHP_en_small.pdf%0D
Resolving www.cres.gr (www.cres.gr)... 195.251.42.4
Connecting to www.cres.gr (www.cres.gr)|195.251.42.4|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:51 ERROR 404: Not Found.

--2020-02-25 22:34:51--  http://www.cres.gr/kape/education/3.CHP_en_small.pdf%0D
Resolving www.cres.gr (www.cres.gr)... 195.251.42.4
Connecting to www.cres.gr (www.cres.gr)|195.251.42.4|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:52 ERROR 404: Not Found.

