--2020-02-25 22:34:46--  http://files.ekt.gr/n020040.pdf%0D
Resolving files.ekt.gr (files.ekt.gr)... 194.177.214.36, 194.177.214.25
Connecting to files.ekt.gr (files.ekt.gr)|194.177.214.36|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:46 ERROR 404: Not Found.

--2020-02-25 22:34:46--  http://files.ekt.gr/n020040.pdf%0D
Resolving files.ekt.gr (files.ekt.gr)... 194.177.214.25, 194.177.214.36
Connecting to files.ekt.gr (files.ekt.gr)|194.177.214.25|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:47 ERROR 404: Not Found.

