--2020-02-25 21:01:42--  http://www.dic.bs/download/ProtectionofDepositorsAct_1.pdf%0D
Resolving www.dic.bs (www.dic.bs)... 208.87.34.100
Connecting to www.dic.bs (www.dic.bs)|208.87.34.100|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:01:42 ERROR 404: Not Found.

--2020-02-25 21:13:10--  http://www.dic.bs/download/ProtectionofDepositorsAct_1.pdf%0D
Resolving www.dic.bs (www.dic.bs)... 208.87.34.100
Connecting to www.dic.bs (www.dic.bs)|208.87.34.100|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:11 ERROR 404: Not Found.

