--2020-02-25 22:35:05--  http://www.hospkorinthos.gr/docs/flu.pdf%0D
Resolving www.hospkorinthos.gr (www.hospkorinthos.gr)... 62.103.107.5
Connecting to www.hospkorinthos.gr (www.hospkorinthos.gr)|62.103.107.5|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:06 ERROR 404: Not Found.

--2020-02-25 22:35:07--  http://www.hospkorinthos.gr/docs/flu.pdf%0D
Resolving www.hospkorinthos.gr (www.hospkorinthos.gr)... 62.103.107.5
Connecting to www.hospkorinthos.gr (www.hospkorinthos.gr)|62.103.107.5|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:08 ERROR 404: Not Found.

