--2020-02-26 00:02:34--  https://soo.nr/jAhZ%0D
Resolving soo.nr (soo.nr)... 99.84.5.115, 99.84.5.51, 99.84.5.126, ...
Connecting to soo.nr (soo.nr)|99.84.5.115|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-26 00:02:35 ERROR 400: Bad Request.

--2020-02-26 00:02:35--  https://soo.nr/oSP0%0D
Resolving soo.nr (soo.nr)... 99.84.5.115, 99.84.5.51, 99.84.5.126, ...
Connecting to soo.nr (soo.nr)|99.84.5.115|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-26 00:02:36 ERROR 400: Bad Request.

