--2020-02-25 22:35:04--  https://www.ose.gr/images/%25CE%2595%25CE%259D%25CE%25A4%25CE%25A5%25CE%25A0%25CE%259F_%25CE%2591%25CE%2599%25CE%25A4%25CE%2597%25CE%25A3%25CE%2597%25CE%25A3_%25CE%25A3%25CE%259F%25CE%25A7_9_2.pdf%0D
Resolving www.ose.gr (www.ose.gr)... 195.167.20.3
Connecting to www.ose.gr (www.ose.gr)|195.167.20.3|:443... connected.
ERROR: cannot verify www.ose.gr's certificate, issued by ‘CN=GeoTrust EV RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to www.ose.gr insecurely, use `--no-check-certificate'.
--2020-02-25 22:35:07--  https://www.ose.gr/images/%25CE%2595%25CE%259D%25CE%25A4%25CE%25A5%25CE%25A0%25CE%259F_%25CE%2591%25CE%2599%25CE%25A4%25CE%2597%25CE%25A3%25CE%2597%25CE%25A3_%25CE%25A3%25CE%259F%25CE%25A7_9_2.pdf%0D
Resolving www.ose.gr (www.ose.gr)... 195.167.20.3
Connecting to www.ose.gr (www.ose.gr)|195.167.20.3|:443... connected.
ERROR: cannot verify www.ose.gr's certificate, issued by ‘CN=GeoTrust EV RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to www.ose.gr insecurely, use `--no-check-certificate'.
