--2020-02-25 22:35:28--  https://www.mamatsio.gr/images/guidelinesfolder/GUIDELINES_OF_PULMONARY_EMBOLISM.pdf%0D
Resolving www.mamatsio.gr (www.mamatsio.gr)... --2020-02-25 22:35:28--  https://www.mamatsio.gr/images/guidelinesfolder/GUIDELINES_OF_PULMONARY_EMBOLISM.pdf%0D
Resolving www.mamatsio.gr (www.mamatsio.gr)... 195.167.83.37
Connecting to www.mamatsio.gr (www.mamatsio.gr)|195.167.83.37|:443... 195.167.83.37
Connecting to www.mamatsio.gr (www.mamatsio.gr)|195.167.83.37|:443... connected.
connected.
ERROR: cannot verify www.mamatsio.gr's certificate, issued by ‘CN=RapidSSL RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to www.mamatsio.gr insecurely, use `--no-check-certificate'.
ERROR: cannot verify www.mamatsio.gr's certificate, issued by ‘CN=RapidSSL RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to www.mamatsio.gr insecurely, use `--no-check-certificate'.
