--2020-02-25 21:56:18--  https://www.sgg.cg/txts-droit-reg/OHADA-Acte-uniforme-2014-societes-commerciales-gie.pdf%0D
Resolving www.sgg.cg (www.sgg.cg)... --2020-02-25 21:56:18--  https://www.sgg.cg/txts-droit-reg/OHADA-Acte-uniforme-2014-societes-commerciales-gie.pdf%0D
Resolving www.sgg.cg (www.sgg.cg)... 213.186.33.4
Connecting to www.sgg.cg (www.sgg.cg)|213.186.33.4|:443... 213.186.33.4
Connecting to www.sgg.cg (www.sgg.cg)|213.186.33.4|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
404 Not Found
2020-02-25 21:56:18 ERROR 404: Not Found.

2020-02-25 21:56:18 ERROR 404: Not Found.

