--2020-02-26 00:02:44--  http://ronlaw.gov.nr/nauru_lpms/files/gazettes/4763a71dcd11c40a3b32ae0f1655b676.pdf%0D
Resolving ronlaw.gov.nr (ronlaw.gov.nr)... 203.98.228.36
Connecting to ronlaw.gov.nr (ronlaw.gov.nr)|203.98.228.36|:80... failed: Connection timed out.
Giving up.

--2020-02-26 00:02:47--  http://ronlaw.gov.nr/nauru_lpms/files/gazettes/c5f7c4f05857204886534eec4a197466.pdf%0D
Resolving ronlaw.gov.nr (ronlaw.gov.nr)... 203.98.228.36
Connecting to ronlaw.gov.nr (ronlaw.gov.nr)|203.98.228.36|:80... failed: Connection timed out.
Giving up.

