--2020-02-25 23:57:32--  https://onequalter.ms/wp-content/uploads/2018/09/building_barriers.pdf%0D
Resolving onequalter.ms (onequalter.ms)... 159.89.90.195
Connecting to onequalter.ms (onequalter.ms)|159.89.90.195|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:33 ERROR 404: Not Found.

--2020-02-25 23:57:33--  https://onequalter.ms/wp-content/uploads/2018/09/building_barriers.pdf%0D
Resolving onequalter.ms (onequalter.ms)... 159.89.90.195
Connecting to onequalter.ms (onequalter.ms)|159.89.90.195|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:34 ERROR 404: Not Found.

