--2020-02-25 22:43:51--  http://www.vaticanobservatory.va/content/dam/specolavaticana/documenti/Workshop_Presentations/02_Filippenko.pdf%0D
Resolving www.vaticanobservatory.va (www.vaticanobservatory.va)... 185.152.70.30
Connecting to www.vaticanobservatory.va (www.vaticanobservatory.va)|185.152.70.30|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:51 ERROR 404: Not Found.

