--2020-02-25 22:35:23--  https://isathens.gr/images/PDFs/vaccinestudies.pdf%0D
--2020-02-25 22:35:23--  https://isathens.gr/images/PDFs/vaccinestudies.pdf%0D
Resolving isathens.gr (isathens.gr)... Resolving isathens.gr (isathens.gr)... 185.78.221.199
Connecting to isathens.gr (isathens.gr)|185.78.221.199|:443... 185.78.221.199
Connecting to isathens.gr (isathens.gr)|185.78.221.199|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.isathens.gr/images/PDFs/vaccinestudies.pdf%0d [following]
--2020-02-25 22:35:23--  https://www.isathens.gr/images/PDFs/vaccinestudies.pdf%0d
Resolving www.isathens.gr (www.isathens.gr)... 301 Moved Permanently
Location: https://www.isathens.gr/images/PDFs/vaccinestudies.pdf%0d [following]
--2020-02-25 22:35:23--  https://www.isathens.gr/images/PDFs/vaccinestudies.pdf%0d
Resolving www.isathens.gr (www.isathens.gr)... 185.78.221.199
Connecting to www.isathens.gr (www.isathens.gr)|185.78.221.199|:443... 185.78.221.199
Connecting to www.isathens.gr (www.isathens.gr)|185.78.221.199|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:24 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:24 ERROR 404: Not Found.

