--2020-02-25 21:01:48--  http://www.wsc.com.bs/WaterandSewerageCorporationAct_1.pdf%0D
Resolving www.wsc.com.bs (www.wsc.com.bs)... 216.172.38.196
Connecting to www.wsc.com.bs (www.wsc.com.bs)|216.172.38.196|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 21:01:49 ERROR 400: Bad Request.

--2020-02-25 21:13:15--  http://www.wsc.com.bs/WaterandSewerageCorporationAct_1.pdf%0D
Resolving www.wsc.com.bs (www.wsc.com.bs)... 216.172.38.196
Connecting to www.wsc.com.bs (www.wsc.com.bs)|216.172.38.196|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 21:13:15 ERROR 400: Bad Request.

