--2020-02-25 23:57:16--  http://www.qci.ms/SP/OB/SilverMaxCommandReference401.pdf%0D
Resolving www.qci.ms (www.qci.ms)... 209.182.193.245
Connecting to www.qci.ms (www.qci.ms)|209.182.193.245|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.quicksilvercontrols.com/SP/OB/SilverMaxCommandReference401.pdf%0d [following]
--2020-02-25 23:57:17--  https://www.quicksilvercontrols.com/SP/OB/SilverMaxCommandReference401.pdf%0d
Resolving www.quicksilvercontrols.com (www.quicksilvercontrols.com)... 209.182.193.245
Connecting to www.quicksilvercontrols.com (www.quicksilvercontrols.com)|209.182.193.245|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:17 ERROR 404: Not Found.

