--2020-02-25 22:35:12--  https://www.e-kyklades.gr/images/pesticides_sector_en_F1023138617.pdf%0D
Resolving www.e-kyklades.gr (www.e-kyklades.gr)... --2020-02-25 22:35:12--  https://www.e-kyklades.gr/images/pesticides_sector_en_F1023138617.pdf%0D
Resolving www.e-kyklades.gr (www.e-kyklades.gr)... 213.16.175.115
Connecting to www.e-kyklades.gr (www.e-kyklades.gr)|213.16.175.115|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:12 ERROR 404: Not Found.

213.16.175.115
Connecting to www.e-kyklades.gr (www.e-kyklades.gr)|213.16.175.115|:443... failed: Connection timed out.
Giving up.

