--2020-02-25 22:34:53--  http://www.tele.gr/PDF3/minitel_1_fin_gr.pdf%0D
Resolving www.tele.gr (www.tele.gr)... 138.201.205.105
Connecting to www.tele.gr (www.tele.gr)|138.201.205.105|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:53 ERROR 404: Not Found.

--2020-02-25 22:34:53--  http://www.tele.gr/PDF3/minitel_1_fin_gr.pdf%0D
Resolving www.tele.gr (www.tele.gr)... 138.201.205.105
Connecting to www.tele.gr (www.tele.gr)|138.201.205.105|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:53 ERROR 404: Not Found.

