--2020-02-25 21:41:22--  https://isoc.td/wp-content/uploads/2018/10/Statut-2018.pdf%0D
Resolving isoc.td (isoc.td)... 141.138.168.120
Connecting to isoc.td (isoc.td)|141.138.168.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:22 ERROR 404: Not Found.

--2020-02-25 21:42:09--  https://isoc.td/wp-content/uploads/2018/10/Statut-2018.pdf%0D
Resolving isoc.td (isoc.td)... 141.138.168.120
Connecting to isoc.td (isoc.td)|141.138.168.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:10 ERROR 404: Not Found.

