--2020-02-25 21:56:26--  https://umng.cg/sites/default/files/Charte%2520The%25CC%2580seUMNG%2520VERSION-29DEC2014.pdf%0D
Resolving umng.cg (umng.cg)... --2020-02-25 21:56:26--  https://umng.cg/sites/default/files/Charte%2520The%25CC%2580seUMNG%2520VERSION-29DEC2014.pdf%0D
Resolving umng.cg (umng.cg)... 162.249.110.58
Connecting to umng.cg (umng.cg)|162.249.110.58|:443... 162.249.110.58
Connecting to umng.cg (umng.cg)|162.249.110.58|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Giving up.

Read error (Connection timed out) in headers.
Giving up.

