--2020-02-25 21:01:56--  https://www.corner.bs/assets/documents/annual_report/ANNUAL_REPORT_NA_2017.pdf%0D
Resolving www.corner.bs (www.corner.bs)... 194.11.213.233
Connecting to www.corner.bs (www.corner.bs)|194.11.213.233|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:01:56 ERROR 404: Not Found.

--2020-02-25 21:13:22--  https://www.corner.bs/assets/documents/annual_report/ANNUAL_REPORT_NA_2017.pdf%0D
Resolving www.corner.bs (www.corner.bs)... 194.11.213.233
Connecting to www.corner.bs (www.corner.bs)|194.11.213.233|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:22 ERROR 404: Not Found.

