--2020-02-25 22:35:28--  https://naxos2018.uest.gr/images/first_draft_NAXOS2018agenda.pdf%0D
Resolving naxos2018.uest.gr (naxos2018.uest.gr)... --2020-02-25 22:35:28--  https://naxos2018.uest.gr/images/first_draft_NAXOS2018agenda.pdf%0D
Resolving naxos2018.uest.gr (naxos2018.uest.gr)... 138.201.252.214
Connecting to naxos2018.uest.gr (naxos2018.uest.gr)|138.201.252.214|:443... 138.201.252.214
Connecting to naxos2018.uest.gr (naxos2018.uest.gr)|138.201.252.214|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

