--2020-02-25 22:34:44--  https://thessaloniki.gr/telkat/%0D
Resolving thessaloniki.gr (thessaloniki.gr)... --2020-02-25 22:34:44--  https://thessaloniki.gr/telkat/%0D
Resolving thessaloniki.gr (thessaloniki.gr)... 84.205.252.236
Connecting to thessaloniki.gr (thessaloniki.gr)|84.205.252.236|:443... connected.
HTTP request sent, awaiting response... 84.205.252.236
Connecting to thessaloniki.gr (thessaloniki.gr)|84.205.252.236|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:46 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:34:46 ERROR 404: Not Found.

