--2020-02-25 21:56:05--  http://www.construction.gouv.cg/documents/loiExercice.pdf%0D
Resolving www.construction.gouv.cg (www.construction.gouv.cg)... 198.136.54.34
Connecting to www.construction.gouv.cg (www.construction.gouv.cg)|198.136.54.34|:80... connected.
HTTP request sent, awaiting response... --2020-02-25 21:56:06--  http://www.construction.gouv.cg/documents/loiExercice.pdf%0D
Resolving www.construction.gouv.cg (www.construction.gouv.cg)... 198.136.54.34
Connecting to www.construction.gouv.cg (www.construction.gouv.cg)|198.136.54.34|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Giving up.

301 Moved Permanently
Location: https://www.construction.gouv.cg/documents/loiExercice.pdf%0d [following]
--2020-02-25 21:56:09--  https://www.construction.gouv.cg/documents/loiExercice.pdf%0d
Connecting to www.construction.gouv.cg (www.construction.gouv.cg)|198.136.54.34|:443... connected.
Unable to establish SSL connection.
