--2020-02-25 22:34:48--  https://www.patakis.gr/images/files/1186439.pdf%0D
Resolving www.patakis.gr (www.patakis.gr)... 51.77.119.153
Connecting to www.patakis.gr (www.patakis.gr)|51.77.119.153|:443... connected.
--2020-02-25 22:34:48--  https://www.patakis.gr/images/files/1186439.pdf%0D
Resolving www.patakis.gr (www.patakis.gr)... HTTP request sent, awaiting response... 51.77.119.153
Connecting to www.patakis.gr (www.patakis.gr)|51.77.119.153|:443... 400 Bad Request
2020-02-25 22:34:48 ERROR 400: Bad Request.

connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:34:48 ERROR 400: Bad Request.

