--2020-02-25 22:35:00--  http://www.pnai.gov.gr/organogramma.pdf%0D
Resolving www.pnai.gov.gr (www.pnai.gov.gr)... 84.205.237.59
Connecting to www.pnai.gov.gr (www.pnai.gov.gr)|84.205.237.59|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:01 ERROR 400: Bad Request.

--2020-02-25 22:35:04--  http://www.pnai.gov.gr/organogramma.pdf%0D
Resolving www.pnai.gov.gr (www.pnai.gov.gr)... 84.205.237.59
Connecting to www.pnai.gov.gr (www.pnai.gov.gr)|84.205.237.59|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:04 ERROR 400: Bad Request.

--2020-02-25 22:35:04--  http://www.pnai.gov.gr/organogramma.pdf%0D
Resolving www.pnai.gov.gr (www.pnai.gov.gr)... 84.205.237.59
Connecting to www.pnai.gov.gr (www.pnai.gov.gr)|84.205.237.59|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:04 ERROR 400: Bad Request.

--2020-02-25 22:35:06--  http://www.pnai.gov.gr/organogramma.pdf%0D
Resolving www.pnai.gov.gr (www.pnai.gov.gr)... 84.205.237.59
Connecting to www.pnai.gov.gr (www.pnai.gov.gr)|84.205.237.59|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:06 ERROR 400: Bad Request.

