--2020-02-25 21:02:21--  http://www.dhl.com.bs/content/dam/downloads/ia_region/express/dhl_importexpress_ug_en.pdf%0D
Resolving www.dhl.com.bs (www.dhl.com.bs)... 104.86.110.147, 104.86.110.138
Connecting to www.dhl.com.bs (www.dhl.com.bs)|104.86.110.147|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:02:21 ERROR 404: Not Found.

--2020-02-25 21:13:42--  http://www.dhl.com.bs/content/dam/downloads/ia_region/express/dhl_importexpress_ug_en.pdf%0D
Resolving www.dhl.com.bs (www.dhl.com.bs)... 104.86.110.147, 104.86.110.138
Connecting to www.dhl.com.bs (www.dhl.com.bs)|104.86.110.147|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:43 ERROR 404: Not Found.

