--2020-02-25 22:34:55--  https://www.bankofgreece.gr/RelatedDocuments/D01_Acornero_Alessandri_Carpinelli_and_Sorrentino.pdf%0D
Resolving www.bankofgreece.gr (www.bankofgreece.gr)... --2020-02-25 22:34:55--  https://www.bankofgreece.gr/RelatedDocuments/D01_Acornero_Alessandri_Carpinelli_and_Sorrentino.pdf%0D
Resolving www.bankofgreece.gr (www.bankofgreece.gr)... 2.18.66.163, 2.18.66.51
Connecting to www.bankofgreece.gr (www.bankofgreece.gr)|2.18.66.163|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:34:56 ERROR 400: Bad Request.

2.18.66.51, 2.18.66.163
Connecting to www.bankofgreece.gr (www.bankofgreece.gr)|2.18.66.51|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:34:56 ERROR 400: Bad Request.

