--2020-02-25 21:02:31--  https://www.bbcc.edu.bs/wp-content/uploads/2018/02/Application-Form.pdf%0D
Resolving www.bbcc.edu.bs (www.bbcc.edu.bs)... 162.241.24.92
Connecting to www.bbcc.edu.bs (www.bbcc.edu.bs)|162.241.24.92|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:02:33 ERROR 404: Not Found.

--2020-02-25 21:13:52--  https://www.bbcc.edu.bs/wp-content/uploads/2018/02/Application-Form.pdf%0D
Resolving www.bbcc.edu.bs (www.bbcc.edu.bs)... 162.241.24.92
Connecting to www.bbcc.edu.bs (www.bbcc.edu.bs)|162.241.24.92|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:53 ERROR 404: Not Found.

