--2020-02-25 22:35:27--  http://www.theaterst.upatras.gr/%3Fp%3D6433%0D
Resolving www.theaterst.upatras.gr (www.theaterst.upatras.gr)... 150.140.202.24
Connecting to www.theaterst.upatras.gr (www.theaterst.upatras.gr)|150.140.202.24|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:27 ERROR 404: Not Found.

--2020-02-25 22:35:28--  http://www.theaterst.upatras.gr/%3Fp%3D6433%0D
Resolving www.theaterst.upatras.gr (www.theaterst.upatras.gr)... 150.140.202.24
Connecting to www.theaterst.upatras.gr (www.theaterst.upatras.gr)|150.140.202.24|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

