--2020-02-25 21:56:08--  http://www.presicongo.cg/files/my_files/consmi110407.pdf%0D
Resolving www.presicongo.cg (www.presicongo.cg)... 81.23.34.170
Connecting to www.presicongo.cg (www.presicongo.cg)|81.23.34.170|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:09 ERROR 404: Not Found.

--2020-02-25 21:56:12--  http://www.presicongo.cg/files/my_files/consmi110407.pdf%0D
Resolving www.presicongo.cg (www.presicongo.cg)... 81.23.34.170
Connecting to www.presicongo.cg (www.presicongo.cg)|81.23.34.170|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:12 ERROR 404: Not Found.

