--2020-02-25 22:35:11--  https://www.bodybuilding.gr/forum/attachment.php%3Fattachmentid%3D85726%26d%3D1405154054%0D
Resolving www.bodybuilding.gr (www.bodybuilding.gr)... --2020-02-25 22:35:11--  https://www.bodybuilding.gr/forum/attachment.php%3Fattachmentid%3D85726%26d%3D1405154054%0D
Resolving www.bodybuilding.gr (www.bodybuilding.gr)... 54.37.165.159
Connecting to www.bodybuilding.gr (www.bodybuilding.gr)|54.37.165.159|:443... 54.37.165.159
Connecting to www.bodybuilding.gr (www.bodybuilding.gr)|54.37.165.159|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:11 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:11 ERROR 404: Not Found.

