--2020-02-25 22:34:48--  https://electron-kriti.gr/files/f701f.pdf%0D
--2020-02-25 22:34:48--  https://electron-kriti.gr/files/f701f.pdf%0D
Resolving electron-kriti.gr (electron-kriti.gr)... Resolving electron-kriti.gr (electron-kriti.gr)... 185.138.42.22
Connecting to electron-kriti.gr (electron-kriti.gr)|185.138.42.22|:443... 185.138.42.22
Connecting to electron-kriti.gr (electron-kriti.gr)|185.138.42.22|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:48 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:34:48 ERROR 404: Not Found.

