--2020-02-25 21:01:46--  http://rbdf.gov.bs/apply.pdf%0D
Resolving rbdf.gov.bs (rbdf.gov.bs)... 162.210.96.115
Connecting to rbdf.gov.bs (rbdf.gov.bs)|162.210.96.115|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:01:48 ERROR 404: Not Found.

--2020-02-25 21:13:13--  http://rbdf.gov.bs/apply.pdf%0D
Resolving rbdf.gov.bs (rbdf.gov.bs)... 162.210.96.115
Connecting to rbdf.gov.bs (rbdf.gov.bs)|162.210.96.115|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:15 ERROR 404: Not Found.

