--2020-02-25 22:35:06--  https://goldenhall.gr/images/GH_Shuttle_Bus.pdf%0D
Resolving goldenhall.gr (goldenhall.gr)... 93.174.121.59
Connecting to goldenhall.gr (goldenhall.gr)|93.174.121.59|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 22:35:07 ERROR 403: Forbidden.

--2020-02-25 22:35:08--  https://goldenhall.gr/images/GH_Shuttle_Bus.pdf%0D
Resolving goldenhall.gr (goldenhall.gr)... 93.174.121.59
Connecting to goldenhall.gr (goldenhall.gr)|93.174.121.59|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 22:35:08 ERROR 403: Forbidden.

