--2020-02-25 23:57:33--  http://preprints.readingroo.ms/Smarandache/NeutrosophyAIDS.pdf%0D
Resolving preprints.readingroo.ms (preprints.readingroo.ms)... 204.13.164.194
Connecting to preprints.readingroo.ms (preprints.readingroo.ms)|204.13.164.194|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:33 ERROR 404: Not Found.

--2020-02-25 23:57:36--  http://preprints.readingroo.ms/Smarandache/NeutrosophyAIDS.pdf%0D
Resolving preprints.readingroo.ms (preprints.readingroo.ms)... 204.13.164.194
Connecting to preprints.readingroo.ms (preprints.readingroo.ms)|204.13.164.194|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:36 ERROR 404: Not Found.

