--2020-02-25 21:56:15--  https://www.pssn.cg/images/Bulletins/VIRUS-INFORMATIQUE.pdf%0D
Resolving www.pssn.cg (www.pssn.cg)... 164.132.235.17
Connecting to www.pssn.cg (www.pssn.cg)|164.132.235.17|:443... connected.
HTTP request sent, awaiting response... --2020-02-25 21:56:15--  https://www.pssn.cg/images/Bulletins/VIRUS-INFORMATIQUE.pdf%0D
Resolving www.pssn.cg (www.pssn.cg)... 164.132.235.17
Connecting to www.pssn.cg (www.pssn.cg)|164.132.235.17|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:16 ERROR 404: Not Found.

404 Not Found
2020-02-25 21:56:16 ERROR 404: Not Found.

