--2020-02-25 21:02:15--  http://ac.cec.edu.bs/html/documents/Academia(September_December2017).pdf%0D
Resolving ac.cec.edu.bs (ac.cec.edu.bs)... 24.244.128.124
Connecting to ac.cec.edu.bs (ac.cec.edu.bs)|24.244.128.124|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 21:02:18 ERROR 403: Forbidden.

--2020-02-25 21:13:40--  http://ac.cec.edu.bs/html/documents/Academia(September_December2017).pdf%0D
Resolving ac.cec.edu.bs (ac.cec.edu.bs)... 24.244.128.124
Connecting to ac.cec.edu.bs (ac.cec.edu.bs)|24.244.128.124|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 21:13:40 ERROR 403: Forbidden.

