--2020-02-25 21:56:01--  http://www.presidence.cg/files/my_files/constit200102.pdf%0D
Resolving www.presidence.cg (www.presidence.cg)... 81.23.34.170
Connecting to www.presidence.cg (www.presidence.cg)|81.23.34.170|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:01 ERROR 404: Not Found.

--2020-02-25 21:56:01--  http://www.presidence.cg/files/my_files/newesp01.pdf%0D
Resolving www.presidence.cg (www.presidence.cg)... 81.23.34.170
Connecting to www.presidence.cg (www.presidence.cg)|81.23.34.170|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:01 ERROR 404: Not Found.

--2020-02-25 21:56:01--  http://www.presidence.cg/files/my_files/constit200102.pdf%0D
Resolving www.presidence.cg (www.presidence.cg)... 81.23.34.170
Connecting to www.presidence.cg (www.presidence.cg)|81.23.34.170|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:02 ERROR 404: Not Found.

--2020-02-25 21:56:02--  http://www.presidence.cg/files/my_files/newesp01.pdf%0D
Resolving www.presidence.cg (www.presidence.cg)... 81.23.34.170
Connecting to www.presidence.cg (www.presidence.cg)|81.23.34.170|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:02 ERROR 404: Not Found.

