--2020-03-02 07:50:50--  http://ml.ms/euid_citi
Resolving ml.ms (ml.ms)... 67.199.248.12, 67.199.248.13
Connecting to ml.ms (ml.ms)|67.199.248.12|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ec.europa.eu/info/law/better-regulation/feedback/12510/attachment/090166e5bc156188_pl [following]
--2020-03-02 07:50:50--  https://ec.europa.eu/info/law/better-regulation/feedback/12510/attachment/090166e5bc156188_pl
Resolving ec.europa.eu (ec.europa.eu)... 147.67.34.30, 147.67.210.30
Connecting to ec.europa.eu (ec.europa.eu)|147.67.34.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/null’

     0K ..                                                     5.20M=0.003s

2020-03-02 07:50:50 (5.20 Mb/s) - ‘/dev/null’ saved [2238]

