--2020-02-25 22:34:50--  http://users.uoa.gr/~atsaoussi/Nalebuff.pdf%0D
Resolving users.uoa.gr (users.uoa.gr)... 195.134.100.68
Connecting to users.uoa.gr (users.uoa.gr)|195.134.100.68|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:50 ERROR 404: Not Found.

--2020-02-25 22:34:51--  http://users.uoa.gr/~atsaoussi/Nalebuff.pdf%0D
Resolving users.uoa.gr (users.uoa.gr)... 195.134.100.68
Connecting to users.uoa.gr (users.uoa.gr)|195.134.100.68|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:51 ERROR 404: Not Found.

