--2020-02-25 21:56:14--  http://www.stanbicbank.cg/standimg/NigeriaGroup/fileDownloads/Stanbic_IBTC_Personal_Account_Trading_Policy_Dec_2018.pdf%0D
Resolving www.stanbicbank.cg (www.stanbicbank.cg)... 196.8.136.20
Connecting to www.stanbicbank.cg (www.stanbicbank.cg)|196.8.136.20|:80... connected.
HTTP request sent, awaiting response... --2020-02-25 21:56:15--  http://www.stanbicbank.cg/standimg/NigeriaGroup/fileDownloads/Stanbic_IBTC_Personal_Account_Trading_Policy_Dec_2018.pdf%0D
Resolving www.stanbicbank.cg (www.stanbicbank.cg)... 196.8.136.20
Connecting to www.stanbicbank.cg (www.stanbicbank.cg)|196.8.136.20|:80... 404 Not Found
2020-02-25 21:56:15 ERROR 404: Not Found.

connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:15 ERROR 404: Not Found.

