--2020-02-25 23:57:38--  http://kosciusko.ms/images/uploads/Kosciusko_Liquor_Ordinance_DraftA.pdf%0D
Resolving kosciusko.ms (kosciusko.ms)... 192.240.185.136
Connecting to kosciusko.ms (kosciusko.ms)|192.240.185.136|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://kosciusko.ms/index.php?/images/uploads/Kosciusko_Liquor_Ordinance_DraftA.pdf%0d [following]
--2020-02-25 23:57:38--  https://kosciusko.ms/index.php?/images/uploads/Kosciusko_Liquor_Ordinance_DraftA.pdf%0d
Connecting to kosciusko.ms (kosciusko.ms)|192.240.185.136|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://kosciusko.ms/?/images/uploads/Kosciusko_Liquor_Ordinance_DraftA.pdf%0d [following]
--2020-02-25 23:57:38--  https://kosciusko.ms/?/images/uploads/Kosciusko_Liquor_Ordinance_DraftA.pdf%0d
Reusing existing connection to kosciusko.ms:443.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:38 ERROR 404: Not Found.

