--2020-02-25 21:41:09--  http://www.ansice.td/W3/images/DECRET074.pdf%0D
Resolving www.ansice.td (www.ansice.td)... 198.54.126.39
Connecting to www.ansice.td (www.ansice.td)|198.54.126.39|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:10 ERROR 404: Not Found.

--2020-02-25 21:41:10--  http://www.ansice.td/W3/images/DECRET079.pdf%0D
Resolving www.ansice.td (www.ansice.td)... 198.54.126.39
Connecting to www.ansice.td (www.ansice.td)|198.54.126.39|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:10 ERROR 404: Not Found.

--2020-02-25 21:42:03--  http://www.ansice.td/W3/images/DECRET074.pdf%0D
Resolving www.ansice.td (www.ansice.td)... 198.54.126.39
Connecting to www.ansice.td (www.ansice.td)|198.54.126.39|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:04 ERROR 404: Not Found.

--2020-02-25 21:42:04--  http://www.ansice.td/W3/images/DECRET079.pdf%0D
Resolving www.ansice.td (www.ansice.td)... 198.54.126.39
Connecting to www.ansice.td (www.ansice.td)|198.54.126.39|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:04 ERROR 404: Not Found.

