--2020-03-02 02:02:35--  http://www.onrtv.td/upld/doc/ar/onrtv-1.pdf
Resolving www.onrtv.td (www.onrtv.td)... 199.16.131.163
Connecting to www.onrtv.td (www.onrtv.td)|199.16.131.163|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42562 (42K) [application/pdf]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .         100% 1.94M=0.2s

2020-03-02 02:02:35 (1.94 Mb/s) - ‘/dev/null’ saved [42562/42562]

