--2020-02-25 21:56:08--  https://www.global-it.cg/images/asecna.pdf%0D
Resolving www.global-it.cg (www.global-it.cg)... 213.186.33.17
Connecting to www.global-it.cg (www.global-it.cg)|213.186.33.17|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:08 ERROR 404: Not Found.

--2020-02-25 21:56:12--  https://www.global-it.cg/images/asecna.pdf%0D
Resolving www.global-it.cg (www.global-it.cg)... 213.186.33.17
Connecting to www.global-it.cg (www.global-it.cg)|213.186.33.17|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:12 ERROR 404: Not Found.

