--2020-02-25 21:55:56--  https://www.acpce.cg/uploads/declaration.pdf%0D
Resolving www.acpce.cg (www.acpce.cg)... --2020-02-25 21:55:56--  https://www.acpce.cg/uploads/declaration.pdf%0D
Resolving www.acpce.cg (www.acpce.cg)... 87.98.154.146
Connecting to www.acpce.cg (www.acpce.cg)|87.98.154.146|:443... connected.
HTTP request sent, awaiting response... 87.98.154.146
Connecting to www.acpce.cg (www.acpce.cg)|87.98.154.146|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:55:57 ERROR 404: Not Found.

404 Not Found
2020-02-25 21:55:57 ERROR 404: Not Found.

