--2020-02-25 21:41:13--  https://finances.gouv.td/images/documents/tresor/2016_Etats_Financiers_NSTT.pdf%0D
Resolving finances.gouv.td (finances.gouv.td)... 213.186.33.16
Connecting to finances.gouv.td (finances.gouv.td)|213.186.33.16|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 21:41:13 ERROR 403: Forbidden.

--2020-02-25 21:42:04--  https://finances.gouv.td/images/documents/tresor/2016_Etats_Financiers_NSTT.pdf%0D
Resolving finances.gouv.td (finances.gouv.td)... 213.186.33.16
Connecting to finances.gouv.td (finances.gouv.td)|213.186.33.16|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 21:42:04 ERROR 403: Forbidden.

