--2020-02-25 21:01:40--  http://www.best.gov.bs/Documents/Bahamas_Biosecurity_Strategy.pdf%0D
Resolving www.best.gov.bs (www.best.gov.bs)... 107.180.47.57
Connecting to www.best.gov.bs (www.best.gov.bs)|107.180.47.57|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:01:41 ERROR 404: Not Found.

--2020-02-25 21:13:08--  http://www.best.gov.bs/Documents/Bahamas_Biosecurity_Strategy.pdf%0D
Resolving www.best.gov.bs (www.best.gov.bs)... 107.180.47.57
Connecting to www.best.gov.bs (www.best.gov.bs)|107.180.47.57|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:09 ERROR 404: Not Found.

