--2020-03-02 08:06:54--  http://agmt.loa.nr/D127B49021.pdf
Resolving agmt.loa.nr (agmt.loa.nr)... 52.216.207.18
Connecting to agmt.loa.nr (agmt.loa.nr)|52.216.207.18|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37819 (37K) []
Saving to: ‘/dev/null’

     0K .......... .......... .......... ......               100% 3.55M=0.09s

2020-03-02 08:06:54 (3.55 Mb/s) - ‘/dev/null’ saved [37819/37819]

