--2020-02-25 23:57:45--  http://agc.gov.ms/wp-content/uploads/2010/02/road_traffic_act.pdf%0D
Resolving agc.gov.ms (agc.gov.ms)... 208.90.112.141
Connecting to agc.gov.ms (agc.gov.ms)|208.90.112.141|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 23:57:45 ERROR 400: Bad Request.

--2020-02-25 23:57:45--  http://agc.gov.ms/wp-content/uploads/2010/02/probation_of_offenders_act.pdf%0D
Resolving agc.gov.ms (agc.gov.ms)... 208.90.112.141
Connecting to agc.gov.ms (agc.gov.ms)|208.90.112.141|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 23:57:45 ERROR 400: Bad Request.

