--2020-02-25 22:43:45--  http://www.vatican.va/news_services/or/or_quo/261q01.pdf%0D
Resolving www.vatican.va (www.vatican.va)... 185.152.70.33
Connecting to www.vatican.va (www.vatican.va)|185.152.70.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:45 ERROR 404: Not Found.

--2020-02-25 22:43:45--  http://www.vatican.va/news_services/or/or_quo/095q01.pdf%0D
Resolving www.vatican.va (www.vatican.va)... 185.152.70.33
Connecting to www.vatican.va (www.vatican.va)|185.152.70.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:45 ERROR 404: Not Found.

