--2020-02-25 21:02:04--  http://www.batelnet.bs/wp-content/uploads/pdfs/A6_ConnectingVIBEBTC.pdf%0D
Resolving www.batelnet.bs (www.batelnet.bs)... 192.185.97.51
Connecting to www.batelnet.bs (www.batelnet.bs)|192.185.97.51|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:02:05 ERROR 404: Not Found.

--2020-02-25 21:13:29--  http://www.batelnet.bs/wp-content/uploads/pdfs/A6_ConnectingVIBEBTC.pdf%0D
Resolving www.batelnet.bs (www.batelnet.bs)... 192.185.97.51
Connecting to www.batelnet.bs (www.batelnet.bs)|192.185.97.51|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:30 ERROR 404: Not Found.

