--2020-02-25 21:41:11--  http://www.audit.arcep.td/forms/Formulaire_station_VSAT.pdf%0D
Resolving www.audit.arcep.td (www.audit.arcep.td)... 199.16.128.113
Connecting to www.audit.arcep.td (www.audit.arcep.td)|199.16.128.113|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:13 ERROR 404: Not Found.

--2020-02-25 21:42:04--  http://www.audit.arcep.td/forms/Formulaire_station_VSAT.pdf%0D
Resolving www.audit.arcep.td (www.audit.arcep.td)... 199.16.128.113
Connecting to www.audit.arcep.td (www.audit.arcep.td)|199.16.128.113|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:04 ERROR 404: Not Found.

