--2020-02-25 22:34:56--  http://www.e-diaxirisi.gr/kanonismos.pdf%0D
Resolving www.e-diaxirisi.gr (www.e-diaxirisi.gr)... --2020-02-25 22:34:56--  http://www.e-diaxirisi.gr/kanonismos.pdf%0D
Resolving www.e-diaxirisi.gr (www.e-diaxirisi.gr)... 192.185.161.150
Connecting to www.e-diaxirisi.gr (www.e-diaxirisi.gr)|192.185.161.150|:80... 192.185.161.150
Connecting to www.e-diaxirisi.gr (www.e-diaxirisi.gr)|192.185.161.150|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:57 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:34:57 ERROR 404: Not Found.

