--2020-02-25 21:41:13--  http://www.google.td/wallet/pdfs/DominosSpecialtyChicken.pdf%0D
Resolving www.google.td (www.google.td)... 172.217.169.67
Connecting to www.google.td (www.google.td)|172.217.169.67|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:13 ERROR 404: Not Found.

--2020-02-25 21:42:04--  http://www.google.td/wallet/pdfs/DominosSpecialtyChicken.pdf%0D
Resolving www.google.td (www.google.td)... 172.217.169.67
Connecting to www.google.td (www.google.td)|172.217.169.67|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:05 ERROR 404: Not Found.

