--2020-02-25 22:35:20--  https://www.normahellas.gr/images/products/14grfile.pdf%0D
Resolving www.normahellas.gr (www.normahellas.gr)... --2020-02-25 22:35:20--  https://www.normahellas.gr/images/products/14grfile.pdf%0D
Resolving www.normahellas.gr (www.normahellas.gr)... 185.25.20.163
Connecting to www.normahellas.gr (www.normahellas.gr)|185.25.20.163|:443... 185.25.20.163
Connecting to www.normahellas.gr (www.normahellas.gr)|185.25.20.163|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:21 ERROR 400: Bad Request.

--2020-02-25 22:35:21--  https://www.normahellas.gr/images/products/26grfile.pdf%0D
Resolving www.normahellas.gr (www.normahellas.gr)... 185.25.20.163
Connecting to www.normahellas.gr (www.normahellas.gr)|185.25.20.163|:443... 400 Bad Request
2020-02-25 22:35:21 ERROR 400: Bad Request.

--2020-02-25 22:35:21--  https://www.normahellas.gr/images/products/26grfile.pdf%0D
Resolving www.normahellas.gr (www.normahellas.gr)... 185.25.20.163
Connecting to www.normahellas.gr (www.normahellas.gr)|185.25.20.163|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:21 ERROR 400: Bad Request.

400 Bad Request
2020-02-25 22:35:21 ERROR 400: Bad Request.

