--2020-02-25 22:35:28--  http://www.dyskolies.gr/files/MD/oikogeneies.pdf%0D
Resolving www.dyskolies.gr (www.dyskolies.gr)... 78.46.83.231
Connecting to www.dyskolies.gr (www.dyskolies.gr)|78.46.83.231|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

--2020-02-25 22:35:28--  http://www.dyskolies.gr/files/MD/oikogeneies.pdf%0D
Resolving www.dyskolies.gr (www.dyskolies.gr)... 78.46.83.231
Connecting to www.dyskolies.gr (www.dyskolies.gr)|78.46.83.231|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

