--2020-03-02 07:51:46--  http://kiwifar.ms/attachments/guntherteschrapsheet-pdf.64305/
Resolving kiwifar.ms (kiwifar.ms)... 104.27.162.162, 104.27.163.162
Connecting to kiwifar.ms (kiwifar.ms)|104.27.162.162|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://kiwifarms.net/attachments/guntherteschrapsheet-pdf.64305/ [following]
--2020-03-02 07:51:46--  https://kiwifarms.net/attachments/guntherteschrapsheet-pdf.64305/
Resolving kiwifarms.net (kiwifarms.net)... 104.26.9.145, 104.26.8.145
Connecting to kiwifarms.net (kiwifarms.net)|104.26.9.145|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 56636 (55K) [application/octet-stream]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 90%  102M 0s
    50K .....                                                 100%  354M=0.004s

2020-03-02 07:51:46 (110 Mb/s) - ‘/dev/null’ saved [56636/56636]

