--2020-02-25 21:55:54--  https://www.congotelecom.cg/cgp.pdf%0D
Resolving www.congotelecom.cg (www.congotelecom.cg)... --2020-02-25 21:55:55--  https://www.congotelecom.cg/cgp.pdf%0D
Resolving www.congotelecom.cg (www.congotelecom.cg)... 50.87.88.46
Connecting to www.congotelecom.cg (www.congotelecom.cg)|50.87.88.46|:443... 50.87.88.46
Connecting to www.congotelecom.cg (www.congotelecom.cg)|50.87.88.46|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:55:55 ERROR 404: Not Found.

404 Not Found
2020-02-25 21:55:55 ERROR 404: Not Found.

