--2020-02-25 22:35:20--  http://agrotikosiatros.gr/documents/AERP-LSUHSC.pdf%0D
Resolving agrotikosiatros.gr (agrotikosiatros.gr)... --2020-02-25 22:35:20--  http://agrotikosiatros.gr/documents/AERP-LSUHSC.pdf%0D
Resolving agrotikosiatros.gr (agrotikosiatros.gr)... 185.25.23.64
Connecting to agrotikosiatros.gr (agrotikosiatros.gr)|185.25.23.64|:80... 185.25.23.64
Connecting to agrotikosiatros.gr (agrotikosiatros.gr)|185.25.23.64|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:20 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:20 ERROR 404: Not Found.

