--2020-02-25 22:34:43--  http://www.dzw.gr/3645e%0D
Resolving www.dzw.gr (www.dzw.gr)... --2020-02-25 22:34:43--  http://www.dzw.gr/3645e%0D
Resolving www.dzw.gr (www.dzw.gr)... 195.72.123.89
Connecting to www.dzw.gr (www.dzw.gr)|195.72.123.89|:80... 195.72.123.89
Connecting to www.dzw.gr (www.dzw.gr)|195.72.123.89|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:34:43 ERROR 400: Bad Request.

400 Bad Request
2020-02-25 22:34:43 ERROR 400: Bad Request.

