--2020-02-25 22:35:27--  http://apografi.gov.gr/images/Evaluation_Manual_Finalization_guide_OCT2018_VERSION_III.pdf%0D
Resolving apografi.gov.gr (apografi.gov.gr)... 84.205.254.114
Connecting to apografi.gov.gr (apografi.gov.gr)|84.205.254.114|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

--2020-02-25 22:35:28--  http://apografi.gov.gr/images/Evaluation_Manual_Finalization_guide_OCT2018_VERSION_III.pdf%0D
Resolving apografi.gov.gr (apografi.gov.gr)... 84.205.254.114
Connecting to apografi.gov.gr (apografi.gov.gr)|84.205.254.114|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:28 ERROR 404: Not Found.

