--2020-02-25 21:02:04--  https://www.infinox.bs/wp-content/uploads/legal/BS_CorporateApplication_EN_V3.pdf%0D
Resolving www.infinox.bs (www.infinox.bs)... 104.18.164.96, 104.18.167.96, 104.18.165.96, ...
Connecting to www.infinox.bs (www.infinox.bs)|104.18.164.96|:443... connected.
HTTP request sent, awaiting response... 520 
2020-02-25 21:02:04 ERROR 520: (no description).

--2020-02-25 21:13:29--  https://www.infinox.bs/wp-content/uploads/legal/BS_CorporateApplication_EN_V3.pdf%0D
Resolving www.infinox.bs (www.infinox.bs)... 104.18.168.96, 104.18.166.96, 104.18.167.96, ...
Connecting to www.infinox.bs (www.infinox.bs)|104.18.168.96|:443... connected.
HTTP request sent, awaiting response... 520 
2020-02-25 21:13:29 ERROR 520: (no description).

