--2020-02-25 22:35:05--  http://www.eof.gr/assets/PL_Tamiflu.pdf%0D
Resolving www.eof.gr (www.eof.gr)... 143.233.208.20
Connecting to www.eof.gr (www.eof.gr)|143.233.208.20|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:05 ERROR 404: Not Found.

--2020-02-25 22:35:07--  http://www.eof.gr/assets/PL_Tamiflu.pdf%0D
Resolving www.eof.gr (www.eof.gr)... 143.233.208.20
Connecting to www.eof.gr (www.eof.gr)|143.233.208.20|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:07 ERROR 404: Not Found.

