--2020-02-25 22:35:25--  https://www.aua.gr/gpapadopoulos/files/distributions.pdf%0D
--2020-02-25 22:35:25--  https://www.aua.gr/gpapadopoulos/files/distributions.pdf%0D
Resolving www.aua.gr (www.aua.gr)... Resolving www.aua.gr (www.aua.gr)... 143.233.204.237
Connecting to www.aua.gr (www.aua.gr)|143.233.204.237|:443... 143.233.204.237
Connecting to www.aua.gr (www.aua.gr)|143.233.204.237|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:25 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:25 ERROR 404: Not Found.

