--2020-02-25 22:35:07--  http://smas.chemeng.ntua.gr/miram/files/publ_359_5_10_2005.pdf%0D
Resolving smas.chemeng.ntua.gr (smas.chemeng.ntua.gr)... 147.102.83.184
Connecting to smas.chemeng.ntua.gr (smas.chemeng.ntua.gr)|147.102.83.184|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 22:35:07 ERROR 403: Forbidden.

--2020-02-25 22:35:09--  http://smas.chemeng.ntua.gr/miram/files/publ_359_5_10_2005.pdf%0D
Resolving smas.chemeng.ntua.gr (smas.chemeng.ntua.gr)... 147.102.83.184
Connecting to smas.chemeng.ntua.gr (smas.chemeng.ntua.gr)|147.102.83.184|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 22:35:09 ERROR 403: Forbidden.

