--2020-02-25 21:41:20--  http://www.haggar.td/wp-content/uploads/2016/06/Article.pdf%0D
Resolving www.haggar.td (www.haggar.td)... 213.186.33.40
Connecting to www.haggar.td (www.haggar.td)|213.186.33.40|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:22 ERROR 404: Not Found.

--2020-02-25 21:42:09--  http://www.haggar.td/wp-content/uploads/2016/06/Article.pdf%0D
Resolving www.haggar.td (www.haggar.td)... 213.186.33.40
Connecting to www.haggar.td (www.haggar.td)|213.186.33.40|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:09 ERROR 404: Not Found.

