--2020-02-25 22:35:20--  https://www.djshop.gr/Attachment/DownloadFile%3FdownloadId%3D5143%0D
Resolving www.djshop.gr (www.djshop.gr)... 138.201.22.88
Connecting to www.djshop.gr (www.djshop.gr)|138.201.22.88|:443... --2020-02-25 22:35:20--  https://www.djshop.gr/Attachment/DownloadFile%3FdownloadId%3D5143%0D
Resolving www.djshop.gr (www.djshop.gr)... 138.201.22.88
Connecting to www.djshop.gr (www.djshop.gr)|138.201.22.88|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:20 ERROR 400: Bad Request.

400 Bad Request
2020-02-25 22:35:20 ERROR 400: Bad Request.

