--2020-02-25 21:02:21--  https://www.mckinney.com.bs/wp-content/uploads/2017/09/mbh__shipping_brochure.pdf%0D
Resolving www.mckinney.com.bs (www.mckinney.com.bs)... 173.255.236.180
Connecting to www.mckinney.com.bs (www.mckinney.com.bs)|173.255.236.180|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:02:22 ERROR 404: Not Found.

--2020-02-25 21:13:43--  https://www.mckinney.com.bs/wp-content/uploads/2017/09/mbh__shipping_brochure.pdf%0D
Resolving www.mckinney.com.bs (www.mckinney.com.bs)... 173.255.236.180
Connecting to www.mckinney.com.bs (www.mckinney.com.bs)|173.255.236.180|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:43 ERROR 404: Not Found.

