--2020-02-25 22:34:53--  http://www.pcci.gr/evepimages/Publicserviceprinciples_EN_F27551.pdf%0D
Resolving www.pcci.gr (www.pcci.gr)... --2020-02-25 22:34:53--  http://www.pcci.gr/evepimages/Publicserviceprinciples_EN_F27551.pdf%0D
Resolving www.pcci.gr (www.pcci.gr)... 193.92.37.201
Connecting to www.pcci.gr (www.pcci.gr)|193.92.37.201|:80... 193.92.37.201
Connecting to www.pcci.gr (www.pcci.gr)|193.92.37.201|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:53 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:34:54 ERROR 404: Not Found.

