--2020-02-25 22:35:06--  http://www.idika.gr/files/TLS_1_2_instructions.pdf%0D
Resolving www.idika.gr (www.idika.gr)... 84.205.251.62
Connecting to www.idika.gr (www.idika.gr)|84.205.251.62|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:06 ERROR 404: Not Found.

--2020-02-25 22:35:08--  http://www.idika.gr/files/TLS_1_2_instructions.pdf%0D
Resolving www.idika.gr (www.idika.gr)... 84.205.251.62
Connecting to www.idika.gr (www.idika.gr)|84.205.251.62|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:08 ERROR 404: Not Found.

