--2020-02-25 21:56:15--  http://score.premierbet.cg/pdf/football-list.pdf%0D
Resolving score.premierbet.cg (score.premierbet.cg)... 193.226.172.80
Connecting to score.premierbet.cg (score.premierbet.cg)|193.226.172.80|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:15 ERROR 404: Not Found.

--2020-02-25 21:56:15--  http://score.premierbet.cg/pdf/football-list.pdf%0D
Resolving score.premierbet.cg (score.premierbet.cg)... 193.226.172.80
Connecting to score.premierbet.cg (score.premierbet.cg)|193.226.172.80|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:15 ERROR 404: Not Found.

