--2020-02-25 22:35:08--  http://www.iasa.gr/EINN_2005/E95_SA.pdf%0D
Resolving www.iasa.gr (www.iasa.gr)... 195.134.89.42, 195.134.89.11
Connecting to www.iasa.gr (www.iasa.gr)|195.134.89.42|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:09 ERROR 404: Not Found.

--2020-02-25 22:35:09--  http://www.iasa.gr/EINN_2005/E95_SA.pdf%0D
Resolving www.iasa.gr (www.iasa.gr)... 195.134.89.11, 195.134.89.42
Connecting to www.iasa.gr (www.iasa.gr)|195.134.89.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:09 ERROR 404: Not Found.

