--2020-02-25 22:34:56--  http://www.tavernarakislab.gr/publications/173.pdf%0D
Resolving www.tavernarakislab.gr (www.tavernarakislab.gr)... --2020-02-25 22:34:56--  http://www.tavernarakislab.gr/publications/173.pdf%0D
Resolving www.tavernarakislab.gr (www.tavernarakislab.gr)... 139.91.171.77
Connecting to www.tavernarakislab.gr (www.tavernarakislab.gr)|139.91.171.77|:80... 139.91.171.77
Connecting to www.tavernarakislab.gr (www.tavernarakislab.gr)|139.91.171.77|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:56 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:34:56 ERROR 404: Not Found.

