--2020-02-25 23:57:45--  http://www.d1.ms/UPLOADS/Documents/DanaosPLATFORM_ADS.pdf%0D
Resolving www.d1.ms (www.d1.ms)... 62.116.130.8
Connecting to www.d1.ms (www.d1.ms)|62.116.130.8|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.danaos1.com/UPLOADS/Documents/DanaosPLATFORM_ADS.pdf\r [following]
--2020-02-25 23:57:45--  http://www.danaos1.com/UPLOADS/Documents/DanaosPLATFORM_ADS.pdf%5Cr
Resolving www.danaos1.com (www.danaos1.com)... 195.97.37.250
Connecting to www.danaos1.com (www.danaos1.com)|195.97.37.250|:80... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://www.danaos1.com/UPLOADS/Documents/DanaosPLATFORM_ADS.pdf/r [following]
--2020-02-25 23:57:45--  https://www.danaos1.com/UPLOADS/Documents/DanaosPLATFORM_ADS.pdf/r
Connecting to www.danaos1.com (www.danaos1.com)|195.97.37.250|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:46 ERROR 404: Not Found.

