--2020-02-25 21:56:17--  http://www.verone.cg/secrets-in-avouables.pdf%0D
Resolving www.verone.cg (www.verone.cg)... --2020-02-25 21:56:17--  http://www.verone.cg/secrets-in-avouables.pdf%0D
Resolving www.verone.cg (www.verone.cg)... 162.241.244.73
Connecting to www.verone.cg (www.verone.cg)|162.241.244.73|:80... 162.241.244.73
Connecting to www.verone.cg (www.verone.cg)|162.241.244.73|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
404 Not Found
2020-02-25 21:56:18 ERROR 404: Not Found.

2020-02-25 21:56:18 ERROR 404: Not Found.

