--2020-02-25 22:35:22--  http://www.eeel.gr/articlefiles/articles/guidelines_for_environmental_infection_control_in_health.pdf%0D
Resolving www.eeel.gr (www.eeel.gr)... --2020-02-25 22:35:22--  http://www.eeel.gr/articlefiles/articles/guidelines_for_environmental_infection_control_in_health.pdf%0D
Resolving www.eeel.gr (www.eeel.gr)... 104.27.175.250, 104.27.174.250
Connecting to www.eeel.gr (www.eeel.gr)|104.27.175.250|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.eeel.gr/articlefiles/articles/guidelines_for_environmental_infection_control_in_health.pdf%0D [following]
--2020-02-25 22:35:22--  https://www.eeel.gr/articlefiles/articles/guidelines_for_environmental_infection_control_in_health.pdf%0D
Connecting to www.eeel.gr (www.eeel.gr)|104.27.175.250|:443... connected.
HTTP request sent, awaiting response... 104.27.175.250, 104.27.174.250
Connecting to www.eeel.gr (www.eeel.gr)|104.27.175.250|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.eeel.gr/articlefiles/articles/guidelines_for_environmental_infection_control_in_health.pdf%0D [following]
--2020-02-25 22:35:22--  https://www.eeel.gr/articlefiles/articles/guidelines_for_environmental_infection_control_in_health.pdf%0D
Connecting to www.eeel.gr (www.eeel.gr)|104.27.175.250|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:22 ERROR 400: Bad Request.

400 Bad Request
2020-02-25 22:35:22 ERROR 400: Bad Request.

