--2020-02-25 22:43:44--  https://www.vaticanlibrary.va/moduli/Regolamento_2016-2017_ITA.pdf%0D
Resolving www.vaticanlibrary.va (www.vaticanlibrary.va)... 212.77.5.67
Connecting to www.vaticanlibrary.va (www.vaticanlibrary.va)|212.77.5.67|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:44 ERROR 404: Not Found.

--2020-02-25 22:43:44--  https://www.vaticanlibrary.va/moduli/Regolamento_2018-2019_ENG.pdf%0D
Resolving www.vaticanlibrary.va (www.vaticanlibrary.va)... 212.77.5.67
Connecting to www.vaticanlibrary.va (www.vaticanlibrary.va)|212.77.5.67|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:45 ERROR 404: Not Found.

