--2020-02-25 22:34:52--  http://www.ergen.gr/files/stock_market_participation.pdf%0D
Resolving www.ergen.gr (www.ergen.gr)... 185.88.20.61
Connecting to www.ergen.gr (www.ergen.gr)|185.88.20.61|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:53 ERROR 404: Not Found.

--2020-02-25 22:34:53--  http://www.ergen.gr/files/stock_market_participation.pdf%0D
Resolving www.ergen.gr (www.ergen.gr)... 185.88.20.61
Connecting to www.ergen.gr (www.ergen.gr)|185.88.20.61|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:53 ERROR 404: Not Found.

