--2020-02-25 22:35:09--  http://users.sch.gr/elnas/joomla2015/images/files/h_klisi_toy_aoristou_b.pdf%0D
Resolving users.sch.gr (users.sch.gr)... 194.63.235.155
Connecting to users.sch.gr (users.sch.gr)|194.63.235.155|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:09 ERROR 404: Not Found.

--2020-02-25 22:35:10--  http://users.sch.gr/elnas/joomla2015/images/files/h_klisi_toy_aoristou_b.pdf%0D
Resolving users.sch.gr (users.sch.gr)... 194.63.235.155
Connecting to users.sch.gr (users.sch.gr)|194.63.235.155|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:10 ERROR 404: Not Found.

