--2020-02-25 21:02:26--  https://inlandrevenue.finance.gov.bs/wp-content/uploads/2018/08/Global20Merchants20July202018.pdf%0D
Resolving inlandrevenue.finance.gov.bs (inlandrevenue.finance.gov.bs)... 108.60.224.235, 24.51.100.235
Connecting to inlandrevenue.finance.gov.bs (inlandrevenue.finance.gov.bs)|108.60.224.235|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:02:28 ERROR 404: Not Found.

--2020-02-25 21:13:47--  https://inlandrevenue.finance.gov.bs/wp-content/uploads/2018/08/Global20Merchants20July202018.pdf%0D
Resolving inlandrevenue.finance.gov.bs (inlandrevenue.finance.gov.bs)... 108.60.224.235, 24.51.100.235
Connecting to inlandrevenue.finance.gov.bs (inlandrevenue.finance.gov.bs)|108.60.224.235|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:49 ERROR 404: Not Found.

