--2020-02-25 22:43:49--  http://www.comunicazione.va/content/dam/comunicazione/services/WorldFeed_ChristmasEve_24_12_2019.pdf%0D
Resolving www.comunicazione.va (www.comunicazione.va)... 185.152.70.101
Connecting to www.comunicazione.va (www.comunicazione.va)|185.152.70.101|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:49 ERROR 404: Not Found.

--2020-02-25 22:43:49--  http://www.comunicazione.va/content/dam/comunicazione/services/Offerta_Pasqua2019_ita_rev1.pdf%0D
Resolving www.comunicazione.va (www.comunicazione.va)... 185.152.70.101
Connecting to www.comunicazione.va (www.comunicazione.va)|185.152.70.101|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:49 ERROR 404: Not Found.

