--2020-02-25 22:35:20--  http://www.filosofia.gr/vivlia/Wittgenstein-Tractatus.pdf%0D
Resolving www.filosofia.gr (www.filosofia.gr)... --2020-02-25 22:35:20--  http://www.filosofia.gr/vivlia/Wittgenstein-Tractatus.pdf%0D
Resolving www.filosofia.gr (www.filosofia.gr)... 82.145.47.118
Connecting to www.filosofia.gr (www.filosofia.gr)|82.145.47.118|:80... 82.145.47.118
Connecting to www.filosofia.gr (www.filosofia.gr)|82.145.47.118|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:20 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:20 ERROR 404: Not Found.

