--2020-02-25 21:01:55--  https://forms.bahamas.gov.bs/documents/LOCGOV_Local_Goverment_Procedure_Manual.pdf%0D
Resolving forms.bahamas.gov.bs (forms.bahamas.gov.bs)... 216.137.8.228, 65.75.74.99
Connecting to forms.bahamas.gov.bs (forms.bahamas.gov.bs)|216.137.8.228|:443... connected.
Unable to establish SSL connection.
--2020-02-25 21:01:56--  https://forms.bahamas.gov.bs/documents/CUST_C13.pdf%0D
Resolving forms.bahamas.gov.bs (forms.bahamas.gov.bs)... 216.137.8.228, 65.75.74.99
Connecting to forms.bahamas.gov.bs (forms.bahamas.gov.bs)|216.137.8.228|:443... connected.
Unable to establish SSL connection.
--2020-02-25 21:13:21--  https://forms.bahamas.gov.bs/documents/LOCGOV_Local_Goverment_Procedure_Manual.pdf%0D
Resolving forms.bahamas.gov.bs (forms.bahamas.gov.bs)... 65.75.74.99, 216.137.8.228
Connecting to forms.bahamas.gov.bs (forms.bahamas.gov.bs)|65.75.74.99|:443... connected.
Unable to establish SSL connection.
--2020-02-25 21:13:22--  https://forms.bahamas.gov.bs/documents/CUST_C13.pdf%0D
Resolving forms.bahamas.gov.bs (forms.bahamas.gov.bs)... 216.137.8.228, 65.75.74.99
Connecting to forms.bahamas.gov.bs (forms.bahamas.gov.bs)|216.137.8.228|:443... connected.
Unable to establish SSL connection.
