--2020-02-25 21:02:18--  https://roadtraffic.gov.bs/wp-content/uploads/2016/04/CabsAct_1.pdf%0D
Resolving roadtraffic.gov.bs (roadtraffic.gov.bs)... 24.51.100.235
Connecting to roadtraffic.gov.bs (roadtraffic.gov.bs)|24.51.100.235|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.roadtraffic.gov.bs/wp-content/uploads/2016/04/CabsAct_1.pdf%0D [following]
--2020-02-25 21:02:19--  https://www.roadtraffic.gov.bs/wp-content/uploads/2016/04/CabsAct_1.pdf%0D
Resolving www.roadtraffic.gov.bs (www.roadtraffic.gov.bs)... 24.51.100.235
Connecting to www.roadtraffic.gov.bs (www.roadtraffic.gov.bs)|24.51.100.235|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:02:21 ERROR 404: Not Found.

--2020-02-25 21:13:40--  https://roadtraffic.gov.bs/wp-content/uploads/2016/04/CabsAct_1.pdf%0D
Resolving roadtraffic.gov.bs (roadtraffic.gov.bs)... 24.51.100.235
Connecting to roadtraffic.gov.bs (roadtraffic.gov.bs)|24.51.100.235|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.roadtraffic.gov.bs/wp-content/uploads/2016/04/CabsAct_1.pdf%0D [following]
--2020-02-25 21:13:41--  https://www.roadtraffic.gov.bs/wp-content/uploads/2016/04/CabsAct_1.pdf%0D
Resolving www.roadtraffic.gov.bs (www.roadtraffic.gov.bs)... 24.51.100.235
Connecting to www.roadtraffic.gov.bs (www.roadtraffic.gov.bs)|24.51.100.235|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:42 ERROR 404: Not Found.

