--2020-02-25 21:02:25--  http://www.tkfoundation.bs/wp-content/uploads/2018/06/2018_Web_Youth-Development_TKFoundation.pdf%0D
Resolving www.tkfoundation.bs (www.tkfoundation.bs)... 104.199.124.8
Connecting to www.tkfoundation.bs (www.tkfoundation.bs)|104.199.124.8|:80... connected.
HTTP request sent, awaiting response... No data received.
Giving up.

--2020-02-25 21:13:46--  http://www.tkfoundation.bs/wp-content/uploads/2018/06/2018_Web_Youth-Development_TKFoundation.pdf%0D
Resolving www.tkfoundation.bs (www.tkfoundation.bs)... 104.199.124.8
Connecting to www.tkfoundation.bs (www.tkfoundation.bs)|104.199.124.8|:80... connected.
HTTP request sent, awaiting response... No data received.
Giving up.

