--2020-02-25 22:34:42--  https://www.fairconsulting.gr/%0D
Resolving www.fairconsulting.gr (www.fairconsulting.gr)... --2020-02-25 22:34:43--  https://www.fairconsulting.gr/%0D
Resolving www.fairconsulting.gr (www.fairconsulting.gr)... 95.216.245.166
Connecting to www.fairconsulting.gr (www.fairconsulting.gr)|95.216.245.166|:443... 95.216.245.166
Connecting to www.fairconsulting.gr (www.fairconsulting.gr)|95.216.245.166|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
404 Not Found
2020-02-25 22:34:43 ERROR 404: Not Found.

2020-02-25 22:34:43 ERROR 404: Not Found.

