--2020-02-25 22:35:11--  http://xeee.web.auth.gr/HCS/HCS_Conf_el/14_presentations_pdf/5_5_Ploutoglou_et_al.pdf%0D
Resolving xeee.web.auth.gr (xeee.web.auth.gr)... --2020-02-25 22:35:11--  http://xeee.web.auth.gr/HCS/HCS_Conf_el/14_presentations_pdf/5_5_Ploutoglou_et_al.pdf%0D
Resolving xeee.web.auth.gr (xeee.web.auth.gr)... 155.207.1.94
Connecting to xeee.web.auth.gr (xeee.web.auth.gr)|155.207.1.94|:80... 155.207.1.94
Connecting to xeee.web.auth.gr (xeee.web.auth.gr)|155.207.1.94|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:11 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:11 ERROR 404: Not Found.

