--2020-02-25 22:35:10--  https://student.cc.uoc.gr/uploadFiles/181-%25CE%2591%25CE%25A3%25CE%25A4%25CE%259A372/WACWUANT_THREEPERNICIOUSPREMISES.pdf%0D
Resolving student.cc.uoc.gr (student.cc.uoc.gr)... --2020-02-25 22:35:10--  https://student.cc.uoc.gr/uploadFiles/181-%25CE%2591%25CE%25A3%25CE%25A4%25CE%259A372/WACWUANT_THREEPERNICIOUSPREMISES.pdf%0D
Resolving student.cc.uoc.gr (student.cc.uoc.gr)... 147.52.200.236
Connecting to student.cc.uoc.gr (student.cc.uoc.gr)|147.52.200.236|:443... 147.52.200.236
Connecting to student.cc.uoc.gr (student.cc.uoc.gr)|147.52.200.236|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:11 ERROR 400: Bad Request.

400 Bad Request
2020-02-25 22:35:11 ERROR 400: Bad Request.

