--2020-02-25 21:56:34--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D
Resolving www.mefdd.cg (www.mefdd.cg)... 51.255.80.200
Connecting to www.mefdd.cg (www.mefdd.cg)|51.255.80.200|:80... connected.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D/ [following]
--2020-02-25 21:56:34--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL Redirect M1362
Location: http://www.mefdd.cg/no_cache/publications [following]
--2020-02-25 21:56:34--  http://www.mefdd.cg/no_cache/publications
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/ [following]
--2020-02-25 21:56:34--  http://www.mefdd.cg/no_cache/publications/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... --2020-02-25 21:56:35--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D
Resolving www.mefdd.cg (www.mefdd.cg)... 51.255.80.200
Connecting to www.mefdd.cg (www.mefdd.cg)|51.255.80.200|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 79135 (77K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 64% 59.5M 0s
    50K .......... .......... .......                         100% 22.6M=0.02s

2020-02-25 21:56:36 (37.8 Mb/s) - ‘/dev/null’ saved [79135/79135]

--2020-02-25 21:56:36--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D
Resolving www.mefdd.cg (www.mefdd.cg)... 51.255.80.200
Connecting to www.mefdd.cg (www.mefdd.cg)|51.255.80.200|:80... connected.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D/ [following]
--2020-02-25 21:56:36--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL Redirect M1362
Location: http://www.mefdd.cg/no_cache/publications [following]
--2020-02-25 21:56:36--  http://www.mefdd.cg/no_cache/publications
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/ [following]
--2020-02-25 21:56:36--  http://www.mefdd.cg/no_cache/publications/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D/ [following]
--2020-02-25 21:56:37--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL Redirect M1362
Location: http://www.mefdd.cg/no_cache/publications [following]
--2020-02-25 21:56:37--  http://www.mefdd.cg/no_cache/publications
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/ [following]
--2020-02-25 21:56:37--  http://www.mefdd.cg/no_cache/publications/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 200 OK
Length: 79135 (77K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 64% 62.4M 0s
    50K .......... .......... .......                         100% 20.6M=0.02s

2020-02-25 21:56:38 (36.4 Mb/s) - ‘/dev/null’ saved [79135/79135]

--2020-02-25 21:56:38--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D
Resolving www.mefdd.cg (www.mefdd.cg)... 51.255.80.200
Connecting to www.mefdd.cg (www.mefdd.cg)|51.255.80.200|:80... connected.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D/ [following]
--2020-02-25 21:56:38--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL Redirect M1362
Location: http://www.mefdd.cg/no_cache/publications [following]
--2020-02-25 21:56:38--  http://www.mefdd.cg/no_cache/publications
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/ [following]
--2020-02-25 21:56:38--  http://www.mefdd.cg/no_cache/publications/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 200 OK
Length: 79135 (77K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 64% 64.8M 0s
    50K .......... .......... .......                         100% 21.4M=0.02s

2020-02-25 21:56:39 (37.8 Mb/s) - ‘/dev/null’ saved [79135/79135]

--2020-02-25 21:56:39--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D
Resolving www.mefdd.cg (www.mefdd.cg)... 51.255.80.200
Connecting to www.mefdd.cg (www.mefdd.cg)|51.255.80.200|:80... connected.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D/ [following]
--2020-02-25 21:56:39--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D53%0D/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL Redirect M1362
Location: http://www.mefdd.cg/no_cache/publications [following]
--2020-02-25 21:56:39--  http://www.mefdd.cg/no_cache/publications
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/ [following]
--2020-02-25 21:56:39--  http://www.mefdd.cg/no_cache/publications/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 200 OK
Length: 79135 (77K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 64% 60.7M 0s
    50K .......... .......... .......                         100% 11.1M=0.03s

2020-02-25 21:56:40 (23.5 Mb/s) - ‘/dev/null’ saved [79135/79135]

--2020-02-25 21:56:40--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D
Resolving www.mefdd.cg (www.mefdd.cg)... 51.255.80.200
Connecting to www.mefdd.cg (www.mefdd.cg)|51.255.80.200|:80... connected.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D/ [following]
--2020-02-25 21:56:40--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL Redirect M1362
Location: http://www.mefdd.cg/no_cache/publications [following]
--2020-02-25 21:56:40--  http://www.mefdd.cg/no_cache/publications
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/ [following]
--2020-02-25 21:56:40--  http://www.mefdd.cg/no_cache/publications/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 200 OK
Length: 79135 (77K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 64% 59.5M 0s
    50K .......... .......... .......                         100% 24.3M=0.02s

2020-02-25 21:56:41 (39.4 Mb/s) - ‘/dev/null’ saved [79135/79135]

--2020-02-25 21:56:41--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D
Resolving www.mefdd.cg (www.mefdd.cg)... 51.255.80.200
Connecting to www.mefdd.cg (www.mefdd.cg)|51.255.80.200|:80... connected.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D/ [following]
--2020-02-25 21:56:41--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL Redirect M1362
Location: http://www.mefdd.cg/no_cache/publications [following]
--2020-02-25 21:56:41--  http://www.mefdd.cg/no_cache/publications
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/ [following]
--2020-02-25 21:56:41--  http://www.mefdd.cg/no_cache/publications/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 200 OK
Length: 79135 (77K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 64% 59.4M 0s
    50K .......... .......... .......                         100% 24.8M=0.02s

2020-02-25 21:56:42 (39.9 Mb/s) - ‘/dev/null’ saved [79135/79135]

200 OK
Length: 79135 (77K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 64% 60.1M 0s
    50K .......... .......... .......                         100% 10.5M=0.03s

2020-02-25 21:56:43 (22.5 Mb/s) - ‘/dev/null’ saved [79135/79135]

--2020-02-25 21:56:43--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D
Resolving www.mefdd.cg (www.mefdd.cg)... 51.255.80.200
Connecting to www.mefdd.cg (www.mefdd.cg)|51.255.80.200|:80... connected.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D/ [following]
--2020-02-25 21:56:44--  http://www.mefdd.cg/no_cache/publications/%3Ftx_abdownloads_pi1%5Baction%5D%3Dgetviewclickeddownload%26tx_abdownloads_pi1%5Buid%5D%3D37%0D/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL Redirect M1362
Location: http://www.mefdd.cg/no_cache/publications [following]
--2020-02-25 21:56:44--  http://www.mefdd.cg/no_cache/publications
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 301 TYPO3 RealURL redirect M961
Location: http://www.mefdd.cg/no_cache/publications/ [following]
--2020-02-25 21:56:44--  http://www.mefdd.cg/no_cache/publications/
Reusing existing connection to www.mefdd.cg:80.
HTTP request sent, awaiting response... 200 OK
Length: 79135 (77K) [text/html]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 64% 61.9M 0s
    50K .......... .......... .......                         100% 9.62M=0.03s

2020-02-25 21:56:45 (21.2 Mb/s) - ‘/dev/null’ saved [79135/79135]

