--2020-02-25 21:41:25--  http://pnd.td/wp-content/uploads/2017/08/PAP-consolid%25C3%25A9.pdf%0D
Resolving pnd.td (pnd.td)... 164.132.235.17
Connecting to pnd.td (pnd.td)|164.132.235.17|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:25 ERROR 404: Not Found.

--2020-02-25 21:42:11--  http://pnd.td/wp-content/uploads/2017/08/PAP-consolid%25C3%25A9.pdf%0D
Resolving pnd.td (pnd.td)... 164.132.235.17
Connecting to pnd.td (pnd.td)|164.132.235.17|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:11 ERROR 404: Not Found.

