--2020-02-26 00:20:48--  http://www.zoning.gov.mp/pubs/57.pdf%0D
Resolving www.zoning.gov.mp (www.zoning.gov.mp)... 199.127.217.52
Connecting to www.zoning.gov.mp (www.zoning.gov.mp)|199.127.217.52|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-26 00:20:49 ERROR 400: Bad Request.

--2020-02-26 00:20:49--  http://www.zoning.gov.mp/pubs/55.pdf%0D
Resolving www.zoning.gov.mp (www.zoning.gov.mp)... 199.127.217.52
Connecting to www.zoning.gov.mp (www.zoning.gov.mp)|199.127.217.52|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-26 00:20:49 ERROR 400: Bad Request.

