--2020-02-25 22:34:50--  http://www.acdcshop.gr/content/INSTR-SIL-ZESTAW_en.pdf%0D
Resolving www.acdcshop.gr (www.acdcshop.gr)... --2020-02-25 22:34:50--  http://www.acdcshop.gr/content/INSTR-SIL-ZESTAW_en.pdf%0D
Resolving www.acdcshop.gr (www.acdcshop.gr)... 85.25.100.116
Connecting to www.acdcshop.gr (www.acdcshop.gr)|85.25.100.116|:80... 85.25.100.116
Connecting to www.acdcshop.gr (www.acdcshop.gr)|85.25.100.116|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:50 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:34:51 ERROR 404: Not Found.

