--2020-02-26 00:21:07--  http://ww.domo.mp/uploads/2016/11/dai2-ensoku.pdf%0D
Resolving ww.domo.mp (ww.domo.mp)... 180.235.234.67
Connecting to ww.domo.mp (ww.domo.mp)|180.235.234.67|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.ainosono.or.jp/uploads/2016/11/dai2-ensoku.pdf%0d [following]
--2020-02-26 00:21:08--  http://www.ainosono.or.jp/uploads/2016/11/dai2-ensoku.pdf%0d
Resolving www.ainosono.or.jp (www.ainosono.or.jp)... 180.235.234.67
Connecting to www.ainosono.or.jp (www.ainosono.or.jp)|180.235.234.67|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-26 00:21:09 ERROR 404: Not Found.

