--2020-02-25 23:57:13--  https://ml.ms/euid_citi%0D
Resolving ml.ms (ml.ms)... 67.199.248.13, 67.199.248.12
Connecting to ml.ms (ml.ms)|67.199.248.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ec.europa.eu/info/law/better-regulation/feedback/12510/attachment/090166e5bc156188_pl [following]
--2020-02-25 23:57:14--  https://ec.europa.eu/info/law/better-regulation/feedback/12510/attachment/090166e5bc156188_pl
Resolving ec.europa.eu (ec.europa.eu)... 147.67.210.30, 147.67.34.30
Connecting to ec.europa.eu (ec.europa.eu)|147.67.210.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/null’

     0K ..                                                     3.05M=0.006s

2020-02-25 23:57:14 (3.05 Mb/s) - ‘/dev/null’ saved [2238]

--2020-02-25 23:57:14--  https://ml.ms/euid_citi%0D
Resolving ml.ms (ml.ms)... 67.199.248.13, 67.199.248.12
Connecting to ml.ms (ml.ms)|67.199.248.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ec.europa.eu/info/law/better-regulation/feedback/12510/attachment/090166e5bc156188_pl [following]
--2020-02-25 23:57:14--  https://ec.europa.eu/info/law/better-regulation/feedback/12510/attachment/090166e5bc156188_pl
Resolving ec.europa.eu (ec.europa.eu)... 147.67.34.30, 147.67.210.30
Connecting to ec.europa.eu (ec.europa.eu)|147.67.34.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/null’

     0K ..                                                     3.87M=0.005s

2020-02-25 23:57:14 (3.87 Mb/s) - ‘/dev/null’ saved [2238]

