--2020-02-25 21:41:06--  https://www.presidence.td/upload/doc/1604.pdf%0D
Resolving www.presidence.td (www.presidence.td)... failed: Connection timed out.
wget: unable to resolve host address ‘www.presidence.td’
--2020-02-25 21:42:03--  https://www.presidence.td/upload/doc/1604.pdf%0D
Resolving www.presidence.td (www.presidence.td)... 199.16.131.246
Connecting to www.presidence.td (www.presidence.td)|199.16.131.246|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:03 ERROR 404: Not Found.

