--2020-02-25 21:02:01--  http://eugenedupuchlaw.edu.bs/files/EDLS-2yr-ApplicationForm.pdf%0D
Resolving eugenedupuchlaw.edu.bs (eugenedupuchlaw.edu.bs)... 184.168.47.225
Connecting to eugenedupuchlaw.edu.bs (eugenedupuchlaw.edu.bs)|184.168.47.225|:80... connected.
HTTP request sent, awaiting response... 404 Not found
2020-02-25 21:02:04 ERROR 404: Not found.

--2020-02-25 21:13:26--  http://eugenedupuchlaw.edu.bs/files/EDLS-2yr-ApplicationForm.pdf%0D
Resolving eugenedupuchlaw.edu.bs (eugenedupuchlaw.edu.bs)... 184.168.47.225
Connecting to eugenedupuchlaw.edu.bs (eugenedupuchlaw.edu.bs)|184.168.47.225|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Giving up.

