--2020-02-25 22:34:43--  http://www.hotelbill.gr/pvsvvka/%0D
Resolving www.hotelbill.gr (www.hotelbill.gr)... --2020-02-25 22:34:43--  http://www.hotelbill.gr/pvsvvka/%0D
Resolving www.hotelbill.gr (www.hotelbill.gr)... 195.154.207.165
Connecting to www.hotelbill.gr (www.hotelbill.gr)|195.154.207.165|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 22:34:43 ERROR 403: Forbidden.

195.154.207.165
Connecting to www.hotelbill.gr (www.hotelbill.gr)|195.154.207.165|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 22:34:43 ERROR 403: Forbidden.

