--2020-02-26 00:20:44--  https://electrici.mp/2NjkVL7%0D
Resolving electrici.mp (electrici.mp)... 67.199.248.13, 67.199.248.12
Connecting to electrici.mp (electrici.mp)|67.199.248.13|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cdn2.hubspot.net/hubfs/2218982/Marketing/Content/Case Studies/Petasense-CaseStudy.pdf?utm_content=77918308&utm_medium=social&utm_source=twitter [following]
--2020-02-26 00:20:44--  https://cdn2.hubspot.net/hubfs/2218982/Marketing/Content/Case%20Studies/Petasense-CaseStudy.pdf?utm_content=77918308&utm_medium=social&utm_source=twitter
Resolving cdn2.hubspot.net (cdn2.hubspot.net)... 104.17.242.204, 104.17.244.204, 104.17.243.204, ...
Connecting to cdn2.hubspot.net (cdn2.hubspot.net)|104.17.242.204|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 294472 (288K) [application/pdf]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 17% 5.69M 0s
    50K .......... .......... .......... .......... .......... 34%  189M 0s
   100K .......... .......... .......... .......... .......... 52% 5.56M 0s
   150K .......... .......... .......... .......... .......... 69%  144M 0s
   200K .......... .......... .......... .......... .......... 86% 3.03G 0s
   250K .......... .......... .......... .......              100%  740M=0.2s

2020-02-26 00:20:45 (15.6 Mb/s) - ‘/dev/null’ saved [294472/294472]

--2020-02-26 00:20:45--  https://electrici.mp/2NjkVL7%0D
Resolving electrici.mp (electrici.mp)... 67.199.248.13, 67.199.248.12
Connecting to electrici.mp (electrici.mp)|67.199.248.13|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cdn2.hubspot.net/hubfs/2218982/Marketing/Content/Case Studies/Petasense-CaseStudy.pdf?utm_content=77918308&utm_medium=social&utm_source=twitter [following]
--2020-02-26 00:20:45--  https://cdn2.hubspot.net/hubfs/2218982/Marketing/Content/Case%20Studies/Petasense-CaseStudy.pdf?utm_content=77918308&utm_medium=social&utm_source=twitter
Resolving cdn2.hubspot.net (cdn2.hubspot.net)... 104.17.241.204, 104.17.242.204, 104.17.244.204, ...
Connecting to cdn2.hubspot.net (cdn2.hubspot.net)|104.17.241.204|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 294472 (288K) [application/pdf]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .......... .......... 17%  382M 0s
    50K .......... .......... .......... .......... .......... 34% 3.51G 0s
   100K .......... .......... .......... .......... .......... 52%  511M 0s
   150K .......... .......... .......... .......... .......... 69% 4.00G 0s
   200K .......... .......... .......... .......... .......... 86% 5.50G 0s
   250K .......... .......... .......... .......              100%  400M=0.003s

2020-02-26 00:20:45 (803 Mb/s) - ‘/dev/null’ saved [294472/294472]

