--2020-02-25 22:35:07--  https://eody.gov.gr/five_keys_food-safety_who_english/%0D
Resolving eody.gov.gr (eody.gov.gr)... 84.205.192.167
Connecting to eody.gov.gr (eody.gov.gr)|84.205.192.167|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:07 ERROR 404: Not Found.

--2020-02-25 22:35:08--  https://eody.gov.gr/five_keys_food-safety_who_english/%0D
Resolving eody.gov.gr (eody.gov.gr)... 84.205.192.167
Connecting to eody.gov.gr (eody.gov.gr)|84.205.192.167|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:08 ERROR 404: Not Found.

