--2020-03-02 07:52:18--  http://www.fbb.ms/img_top_menu/files_rtf_doc/prayers/JERICHO_webE.pdf
Resolving www.fbb.ms (www.fbb.ms)... 192.3.201.65
Connecting to www.fbb.ms (www.fbb.ms)|192.3.201.65|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40037 (39K) [application/pdf]
Saving to: ‘/dev/null’

     0K .......... .......... .......... .........            100% 1.88M=0.2s

2020-03-02 07:52:18 (1.88 Mb/s) - ‘/dev/null’ saved [40037/40037]

