--2020-02-25 22:35:01--  http://www.komvos.edu.gr/Lexiko_alfabhtika.pdf%0D
Resolving www.komvos.edu.gr (www.komvos.edu.gr)... 160.40.50.150
Connecting to www.komvos.edu.gr (www.komvos.edu.gr)|160.40.50.150|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:02 ERROR 404: Not Found.

--2020-02-25 22:35:04--  http://www.komvos.edu.gr/Lexiko_alfabhtika.pdf%0D
Resolving www.komvos.edu.gr (www.komvos.edu.gr)... 160.40.50.150
Connecting to www.komvos.edu.gr (www.komvos.edu.gr)|160.40.50.150|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:05 ERROR 404: Not Found.

