--2020-02-25 22:34:54--  http://www.epitropakisg.gr/grigorise/PBL_Research.pdf%0D
Resolving www.epitropakisg.gr (www.epitropakisg.gr)... --2020-02-25 22:34:54--  http://www.epitropakisg.gr/grigorise/PBL_Research.pdf%0D
Resolving www.epitropakisg.gr (www.epitropakisg.gr)... 67.225.208.195
Connecting to www.epitropakisg.gr (www.epitropakisg.gr)|67.225.208.195|:80... 67.225.208.195
Connecting to www.epitropakisg.gr (www.epitropakisg.gr)|67.225.208.195|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:34:54 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:34:54 ERROR 404: Not Found.

