--2020-02-25 21:56:18--  https://www.airfrance.cg/common/image/pdf/fr/pmr_formulaire_B_fr.pdf%0D
Resolving www.airfrance.cg (www.airfrance.cg)... --2020-02-25 21:56:18--  https://www.airfrance.cg/common/image/pdf/fr/pmr_formulaire_B_fr.pdf%0D
Resolving www.airfrance.cg (www.airfrance.cg)... 2.22.140.240
Connecting to www.airfrance.cg (www.airfrance.cg)|2.22.140.240|:443... 2.22.140.240
Connecting to www.airfrance.cg (www.airfrance.cg)|2.22.140.240|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Giving up.

Read error (Connection timed out) in headers.
Giving up.

