--2020-02-25 22:35:25--  https://array.gr/itemfiles-en/358.pdf%0D
--2020-02-25 22:35:25--  https://array.gr/itemfiles-en/358.pdf%0D
Resolving array.gr (array.gr)... Resolving array.gr (array.gr)... 78.46.101.226
Connecting to array.gr (array.gr)|78.46.101.226|:443... connected.
78.46.101.226
Connecting to array.gr (array.gr)|78.46.101.226|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:25 ERROR 404: Not Found.

HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:25 ERROR 404: Not Found.

