--2020-02-25 22:35:29--  http://dlib.statistics.gr/Book/GRESYE_02_1301_00004.pdf%0D
Resolving dlib.statistics.gr (dlib.statistics.gr)... --2020-02-25 22:35:29--  http://dlib.statistics.gr/Book/GRESYE_02_1301_00004.pdf%0D
Resolving dlib.statistics.gr (dlib.statistics.gr)... 84.205.246.27
Connecting to dlib.statistics.gr (dlib.statistics.gr)|84.205.246.27|:80... 84.205.246.27
Connecting to dlib.statistics.gr (dlib.statistics.gr)|84.205.246.27|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-25 22:35:29 ERROR 403: Forbidden.

403 Forbidden
2020-02-25 22:35:29 ERROR 403: Forbidden.

