--2020-02-25 21:56:10--  http://www.carlsonwagonlit.cg/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0D
Resolving www.carlsonwagonlit.cg (www.carlsonwagonlit.cg)... 104.86.133.150
Connecting to www.carlsonwagonlit.cg (www.carlsonwagonlit.cg)|104.86.133.150|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.mycwt.com/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0d [following]
--2020-02-25 21:56:11--  https://www.mycwt.com/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0d
Resolving www.mycwt.com (www.mycwt.com)... 104.86.133.150
Connecting to www.mycwt.com (www.mycwt.com)|104.86.133.150|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.mycwt.com/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0d/ [following]
--2020-02-25 21:56:11--  https://www.mycwt.com/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0d/
Reusing existing connection to www.mycwt.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:14 ERROR 404: Not Found.

--2020-02-25 21:56:14--  http://www.carlsonwagonlit.cg/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0D
Resolving www.carlsonwagonlit.cg (www.carlsonwagonlit.cg)... 104.86.133.150
Connecting to www.carlsonwagonlit.cg (www.carlsonwagonlit.cg)|104.86.133.150|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.mycwt.com/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0d [following]
--2020-02-25 21:56:14--  https://www.mycwt.com/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0d
Resolving www.mycwt.com (www.mycwt.com)... 104.86.133.150
Connecting to www.mycwt.com (www.mycwt.com)|104.86.133.150|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.mycwt.com/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0d/ [following]
--2020-02-25 21:56:14--  https://www.mycwt.com/content/dam/cwt/countries/de/pdf/studie_compliance_en.pdf%0d/
Reusing existing connection to www.mycwt.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:56:14 ERROR 404: Not Found.

