--2020-02-25 22:43:51--  http://www.laityfamilylife.va/content/dam/laityfamilylife/Magistero/FamigliaEng/006_ENG_Codice_di_diritto_Canonico_2_di_2_can_da_1055_a_1165.pdf%0D
Resolving www.laityfamilylife.va (www.laityfamilylife.va)... 185.152.70.30
Connecting to www.laityfamilylife.va (www.laityfamilylife.va)|185.152.70.30|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:51 ERROR 404: Not Found.

--2020-02-25 22:43:51--  http://www.laityfamilylife.va/content/dam/laityfamilylife/Magistero/FamigliaEng/007_ENG_Catechismo_della_Chiesa_Cattolica_1_di_5_nn_da_1601_a_1666.pdf%0D
Resolving www.laityfamilylife.va (www.laityfamilylife.va)... 185.152.70.30
Connecting to www.laityfamilylife.va (www.laityfamilylife.va)|185.152.70.30|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:43:51 ERROR 404: Not Found.

