--2020-02-25 21:41:17--  https://www.enastic.td/wp-content/uploads/2018/01/Programme_licence_management_des_TIC.pdf%0D
Resolving www.enastic.td (www.enastic.td)... 212.129.45.189
Connecting to www.enastic.td (www.enastic.td)|212.129.45.189|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:19 ERROR 404: Not Found.

--2020-02-25 21:41:19--  https://www.enastic.td/wp-content/uploads/2018/01/Programme_licence_telecommunications.pdf%0D
Resolving www.enastic.td (www.enastic.td)... 212.129.45.189
Connecting to www.enastic.td (www.enastic.td)|212.129.45.189|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:41:20 ERROR 404: Not Found.

--2020-02-25 21:42:08--  https://www.enastic.td/wp-content/uploads/2018/01/Programme_licence_management_des_TIC.pdf%0D
Resolving www.enastic.td (www.enastic.td)... 212.129.45.189
Connecting to www.enastic.td (www.enastic.td)|212.129.45.189|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:08 ERROR 404: Not Found.

--2020-02-25 21:42:08--  https://www.enastic.td/wp-content/uploads/2018/01/Programme_licence_telecommunications.pdf%0D
Resolving www.enastic.td (www.enastic.td)... 212.129.45.189
Connecting to www.enastic.td (www.enastic.td)|212.129.45.189|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:42:09 ERROR 404: Not Found.

