--2020-02-25 21:02:22--  https://nagb.org.bs/s/NAGB-Teachers-Packet-2016-small.pdf%0D
Resolving nagb.org.bs (nagb.org.bs)... 198.49.23.144, 198.49.23.145, 198.185.159.145, ...
Connecting to nagb.org.bs (nagb.org.bs)|198.49.23.144|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:02:23 ERROR 404: Not Found.

--2020-02-25 21:13:44--  https://nagb.org.bs/s/NAGB-Teachers-Packet-2016-small.pdf%0D
Resolving nagb.org.bs (nagb.org.bs)... 198.49.23.144, 198.185.159.144, 198.49.23.145, ...
Connecting to nagb.org.bs (nagb.org.bs)|198.49.23.144|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:44 ERROR 404: Not Found.

