--2020-02-25 21:55:56--  http://boursesdecooperation-mesup.cg/chine.pdf%0D
Resolving boursesdecooperation-mesup.cg (boursesdecooperation-mesup.cg)... --2020-02-25 21:55:56--  http://boursesdecooperation-mesup.cg/chine.pdf%0D
Resolving boursesdecooperation-mesup.cg (boursesdecooperation-mesup.cg)... failed: Name or service not known.
wget: unable to resolve host address ‘boursesdecooperation-mesup.cg’
failed: Name or service not known.
wget: unable to resolve host address ‘boursesdecooperation-mesup.cg’
