--2020-02-25 22:35:09--  http://www.isserron.gr/pdf/ipodeigma.pdf%0D
Resolving www.isserron.gr (www.isserron.gr)... 195.170.8.107
Connecting to www.isserron.gr (www.isserron.gr)|195.170.8.107|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:09 ERROR 400: Bad Request.

--2020-02-25 22:35:10--  http://www.isserron.gr/pdf/ipodeigma.pdf%0D
Resolving www.isserron.gr (www.isserron.gr)... 195.170.8.107
Connecting to www.isserron.gr (www.isserron.gr)|195.170.8.107|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-02-25 22:35:10 ERROR 400: Bad Request.

