--2020-02-25 22:35:07--  http://www.wwf.gr/images/pdfs/Reviving_Mediterranean_Sea_Economy_Full%2520rep_Lowres.pdf%0D
Resolving www.wwf.gr (www.wwf.gr)... 93.104.213.243
Connecting to www.wwf.gr (www.wwf.gr)|93.104.213.243|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.wwf.gr/images/pdfs/Reviving_Mediterranean_Sea_Economy_Full%2520rep_Lowres.pdf%0D [following]
--2020-02-25 22:35:08--  https://www.wwf.gr/images/pdfs/Reviving_Mediterranean_Sea_Economy_Full%2520rep_Lowres.pdf%0D
Connecting to www.wwf.gr (www.wwf.gr)|93.104.213.243|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:08 ERROR 404: Not Found.

--2020-02-25 22:35:09--  http://www.wwf.gr/images/pdfs/Reviving_Mediterranean_Sea_Economy_Full%2520rep_Lowres.pdf%0D
Resolving www.wwf.gr (www.wwf.gr)... 93.104.213.243
Connecting to www.wwf.gr (www.wwf.gr)|93.104.213.243|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.wwf.gr/images/pdfs/Reviving_Mediterranean_Sea_Economy_Full%2520rep_Lowres.pdf%0D [following]
--2020-02-25 22:35:09--  https://www.wwf.gr/images/pdfs/Reviving_Mediterranean_Sea_Economy_Full%2520rep_Lowres.pdf%0D
Connecting to www.wwf.gr (www.wwf.gr)|93.104.213.243|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:09 ERROR 404: Not Found.

