--2020-02-25 22:35:21--  http://ensconet.maich.gr/PDF/Collecting_protocol_German.pdf%0D
Resolving ensconet.maich.gr (ensconet.maich.gr)... --2020-02-25 22:35:21--  http://ensconet.maich.gr/PDF/Collecting_protocol_German.pdf%0D
Resolving ensconet.maich.gr (ensconet.maich.gr)... 193.218.36.14
Connecting to ensconet.maich.gr (ensconet.maich.gr)|193.218.36.14|:80... 193.218.36.14
Connecting to ensconet.maich.gr (ensconet.maich.gr)|193.218.36.14|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 22:35:22 ERROR 404: Not Found.

404 Not Found
2020-02-25 22:35:22 ERROR 404: Not Found.

