--2020-02-26 00:20:49--  http://www.mugishin.soaweb.mp/hs_data/Image/2018spr2025_kosaimiyakoda.pdf%0D
Resolving www.mugishin.soaweb.mp (www.mugishin.soaweb.mp)... 27.34.160.59
Connecting to www.mugishin.soaweb.mp (www.mugishin.soaweb.mp)|27.34.160.59|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.mugishin.co.jp/hs_data/Image/2018spr2025_kosaimiyakoda.pdf%0d [following]
--2020-02-26 00:20:50--  https://www.mugishin.co.jp/hs_data/Image/2018spr2025_kosaimiyakoda.pdf%0d
Resolving www.mugishin.co.jp (www.mugishin.co.jp)... 180.235.235.21
Connecting to www.mugishin.co.jp (www.mugishin.co.jp)|180.235.235.21|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-26 00:20:52 ERROR 404: Not Found.

--2020-02-26 00:20:52--  http://www.mugishin.soaweb.mp/hs_data/Image/toshin_20161015.pdf%0D
Resolving www.mugishin.soaweb.mp (www.mugishin.soaweb.mp)... 27.34.160.59
Connecting to www.mugishin.soaweb.mp (www.mugishin.soaweb.mp)|27.34.160.59|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.mugishin.co.jp/hs_data/Image/toshin_20161015.pdf%0d [following]
--2020-02-26 00:20:52--  https://www.mugishin.co.jp/hs_data/Image/toshin_20161015.pdf%0d
Resolving www.mugishin.co.jp (www.mugishin.co.jp)... 180.235.235.21
Connecting to www.mugishin.co.jp (www.mugishin.co.jp)|180.235.235.21|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-26 00:20:53 ERROR 404: Not Found.

