--2020-02-25 21:01:35--  http://www.bmg.bs/100joor/pdf/joorhundertblatt.pdf%0D
Resolving www.bmg.bs (www.bmg.bs)... 85.10.194.214
Connecting to www.bmg.bs (www.bmg.bs)|85.10.194.214|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.bmg.bs/100joor/pdf/joorhundertblatt.pdf%0d [following]
--2020-02-25 21:01:36--  https://www.bmg.bs/100joor/pdf/joorhundertblatt.pdf%0d
Connecting to www.bmg.bs (www.bmg.bs)|85.10.194.214|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:01:36 ERROR 404: Not Found.

--2020-02-25 21:13:05--  http://www.bmg.bs/100joor/pdf/joorhundertblatt.pdf%0D
Resolving www.bmg.bs (www.bmg.bs)... 85.10.194.214
Connecting to www.bmg.bs (www.bmg.bs)|85.10.194.214|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.bmg.bs/100joor/pdf/joorhundertblatt.pdf%0d [following]
--2020-02-25 21:13:05--  https://www.bmg.bs/100joor/pdf/joorhundertblatt.pdf%0d
Connecting to www.bmg.bs (www.bmg.bs)|85.10.194.214|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:13:05 ERROR 404: Not Found.

