--2020-02-25 23:57:33--  https://instrument.ms/statics/media/5cda76619f4fc.pdf%0D
Resolving instrument.ms (instrument.ms)... 185.87.193.140
Connecting to instrument.ms (instrument.ms)|185.87.193.140|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:33 ERROR 404: Not Found.

--2020-02-25 23:57:36--  https://instrument.ms/statics/media/5d01ecb66d398.pdf%0D
Resolving instrument.ms (instrument.ms)... 185.87.193.140
Connecting to instrument.ms (instrument.ms)|185.87.193.140|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:36 ERROR 404: Not Found.

--2020-02-25 23:57:36--  https://instrument.ms/statics/media/5c47081a74103.pdf%0D
Resolving instrument.ms (instrument.ms)... 185.87.193.140
Connecting to instrument.ms (instrument.ms)|185.87.193.140|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 23:57:36 ERROR 404: Not Found.

