--2020-02-25 21:55:55--  http://archive.dgden.cg/14_juin_2018.pdf%0D
Resolving archive.dgden.cg (archive.dgden.cg)... --2020-02-25 21:55:55--  http://archive.dgden.cg/14_juin_2018.pdf%0D
Resolving archive.dgden.cg (archive.dgden.cg)... 91.234.194.177
Connecting to archive.dgden.cg (archive.dgden.cg)|91.234.194.177|:80... 91.234.194.177
Connecting to archive.dgden.cg (archive.dgden.cg)|91.234.194.177|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://archive.dgden.cg/14_juin_2018.pdf%0d [following]
--2020-02-25 21:55:55--  https://archive.dgden.cg/14_juin_2018.pdf%0d
Connecting to archive.dgden.cg (archive.dgden.cg)|91.234.194.177|:443... 301 Moved Permanently
Location: https://archive.dgden.cg/14_juin_2018.pdf%0d [following]
--2020-02-25 21:55:55--  https://archive.dgden.cg/14_juin_2018.pdf%0d
Connecting to archive.dgden.cg (archive.dgden.cg)|91.234.194.177|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:55:55 ERROR 404: Not Found.

404 Not Found
2020-02-25 21:55:55 ERROR 404: Not Found.

--2020-02-25 21:55:55--  http://archive.dgden.cg/20_septembre_2018.pdf%0D
Resolving archive.dgden.cg (archive.dgden.cg)... 91.234.194.177
Connecting to archive.dgden.cg (archive.dgden.cg)|91.234.194.177|:80... --2020-02-25 21:55:56--  http://archive.dgden.cg/20_septembre_2018.pdf%0D
Resolving archive.dgden.cg (archive.dgden.cg)... 91.234.194.177
Connecting to archive.dgden.cg (archive.dgden.cg)|91.234.194.177|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://archive.dgden.cg/20_septembre_2018.pdf%0d [following]
--2020-02-25 21:55:56--  https://archive.dgden.cg/20_septembre_2018.pdf%0d
Connecting to archive.dgden.cg (archive.dgden.cg)|91.234.194.177|:443... 301 Moved Permanently
Location: https://archive.dgden.cg/20_septembre_2018.pdf%0d [following]
--2020-02-25 21:55:56--  https://archive.dgden.cg/20_septembre_2018.pdf%0d
Connecting to archive.dgden.cg (archive.dgden.cg)|91.234.194.177|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2020-02-25 21:55:56 ERROR 404: Not Found.

404 Not Found
2020-02-25 21:55:56 ERROR 404: Not Found.

